#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_aufs(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(local_agents_dir + "/plugins/check_aufs", plugins_dir + "/check_aufs")

bakery_info["aufs"] = {
    "bake_function" : bake_aufs,
    "os"            : [ "linux", ],
}
