#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def bake_sap_hana(opsys, conf, conf_dir, plugins_dir):
    if opsys == "linux":
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/sap_hana", plugins_dir + "/sap_hana")
        if 'auth' in conf or 'runas' in conf:
            f = file(conf_dir + "/sap_hana.cfg", "w")
            f.write(agent_file_header)
            if 'auth' in conf:
                if conf['auth'][0] == 'store':
                    f.write('USERSTOREKEY=%s\n' % conf['auth'][1][0])
                elif conf['auth'][0] == 'explicit':
                    f.write('USER=%s\n' % conf['auth'][1][0])
                    if conf['auth'][1][1][0] == 'password':
                        f.write('PASSWORD=%s\n' % conf['auth'][1][1][1])
                    elif conf['auth'][1][1][0] == 'store':
                        passwords = cmk.password_store.load()
                        f.write('PASSWORD=%s\n' % passwords[conf['auth'][1][1][1]])
            if 'runas' in conf:
                f.write('RUNAS=%s\n' % conf['runas'])

bakery_info["sap_hana"] = {
    "bake_function" : bake_sap_hana,
    "os"            : [ "linux" ],
    "matchtype"     : "first",
}
