#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

def check_ssh_arguments(params):
    settings = params[0]

    if 'hostname' in settings:
        args = "-H %s" % quote_shell_string(settings['hostname'])
    else:
        args = "-H $HOSTADDRESS$"

    if "port" in settings:
        args += " -p %d" % settings["port"]
        
    if "ip_version" in settings:
        if settings['ip_version'] == 'ipv4':
            args += ' -4'
        else:
            args += ' -6'

    if "timeout" in settings:
        args += ' -t %d' % settings["timeout"]

    if "remote-version" in settings:
        args += ' -r %s' % quote_shell_string(settings["remote-version"])

    return args

def check_ssh_description(params):
    settings = params[0]

    description = "SSH"

    if 'hostname' in settings and '$' not in settings['hostname']:
        description += " %s" % settings['hostname']

    if 'port' in settings:
        description += " Port %s" % settings['port']

    return description

active_check_info['ssh'] = {
    "command_line"        : '$USER1$/check_ssh $ARG1$',
    "argument_function"   : check_ssh_arguments,
    "service_description" : check_ssh_description ,
    "has_perfdata"        : True,
}


