#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (C) 2019 Heinlein Support GmbH
# Robert Sander <r.sander@heinlein-support.de>
#

def agent_jenkinsjobs_arguments(servicespecs, hostname, ipaddress):    
    params = {'servicespecs': servicespecs,
              'hostname': hostname,
              'ipadress': ipaddress}

    from pickle import dumps
    from base64 import encodestring

    cmd = []

    cmd += encodestring(dumps(params)).decode('ascii').split('\n')

    return " ".join(cmd)

special_agent_info['jenkinsjobs'] = agent_jenkinsjobs_arguments
