#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

## factory_settings["printer_used_ricoh_default_levels"] = {
##     "levels" : ( 20.0, 10.0 )
## }

_ricoh_used = {
    '8': 'pages printed',
    '50': 'cartridges used',
    }

def inventory_printer_used_ricoh(info):
    counter = [
        u'Counter: Machine Total',
        u'Counter: Black & White',
        u'Counter: Economy Color',
        u'Counter: Full Color',
        u'Cartridge Use Number: Black',
        u'Cartridge Use Number: Cyan',
        u'Cartridge Use Number: Magenta',
        u'Cartridge Use Number: Yellow',
        ]

    for line in info:
        if line[3] in counter:
            yield line[3], {}

def check_printer_used_ricoh(item, params, info):
    for line in info:
        name = line[3]
        if item == name:

            state = 0
            value = saveint(line[7])
            

            infotext = "%s: %d %s" % ( line[4], value, _ricoh_used.get(line[2]) )

            if "black" in name.lower():
                perf_type = "black"
            elif "cyan" in name.lower():
                perf_type = "cyan"
            elif "magenta" in name.lower():
                perf_type = "magenta"
            elif "yellow" in name.lower():
                perf_type = "yellow"
            else:
                perf_type = "other"

            perfdata = [ ("%s_%s" % ("_".join(_ricoh_used.get(line[2], "unknown").split()),perf_type), value) ]

            return state, infotext, perfdata

check_info['printer_used_ricoh'] = {
    "inventory_function"      : inventory_printer_used_ricoh,
    "check_function"          : check_printer_used_ricoh,
    "service_description"     : "Ricoh %s",
    "has_perfdata"            : True,
    # "group"                   : "printer_used",
    "snmp_info"               : ( ".1.3.6.1.4.1.367.3.2.1.2.19.5.1", [ 2,3,4,5,6,7,8, 9 ] ),
    "snmp_scan_function"      : lambda oid: oid(".1.3.6.1.2.1.1.2.0") in [ ".1.3.6.1.4.1.367.1.1" ],
    # "default_levels_variable" : "printer_used_ricoh_default_levels",
}
