#!/bin/bash

lsbrelease=$(which lsb_release)

if [ -x "$lsbrelease" ]; then

    echo '<<<lsbrelease>>>'

    if [ -r /etc/SuSE-release ]; then
        version=$(grep ^VERSION /etc/SuSE-release | cut -f 3 -d " ")
        patchlevel=$(grep ^PATCHLEVEL /etc/SuSE-release | cut -f 3 -d " ")
        if [ -n "$patchlevel" ]; then
            version="$version.$patchlevel"
        fi
        if [ -n "$version" ]; then
            $lsbrelease -a |grep -v ^Release
            echo -e "Release:\t$version"
        else
            $lsbrelease -a
        fi
    else
        $lsbrelease -a
    fi

fi

