#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_dirvish(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(local_agents_dir + "/plugins/dirvish", plugins_dir + "/dirvish")
    f = file(conf_dir + "/dirvish", "w")
    f.write(agent_file_header)

    if conf.has_key("bank"):
        f.write("bank=\"%s\"\n" % conf["bank"])

bakery_info["dirvish"] = {
    "bake_function" : bake_dirvish,
    "os"            : [ "linux", ],
}
