#!/bin/bash

MYCNF=/etc/mysql/my.cnf
WARN=60
CRIT=3600

TIMESTAMP=$MK_VARDIR/galerastartup.timestamp

function checkinfile()
{
    filename="$1"
    if grep -q ^wsrep_cluster_address "$filename"; then
        if [ $(dirname $0) != "$MK_LIBDIR/local" ]; then
            echo '<<<local>>>'
        fi
	if grep -q '^wsrep_cluster_address="gcomm://"' $filename; then
	    if [ ! -e $TIMESTAMP ]; then
		touch $TIMESTAMP
	    fi
	    filedate=$(stat -c '%Z' $TIMESTAMP)
	    now=$(date '+%s')
	    echo "P GaleraStartup age=$(($now - $filedate));$WARN;$CRIT;0 Galera Startup cluster address not set in $filename"
	else
	    rm -f $TIMESTAMP
	    echo "0 GaleraStartup age=0;$WARN;$CRIT;0 Galera Startup cluster address in $filename is OK"
	fi
    fi
    for includefile in $(grep '^\!include ' "$filename" | cut -f 2- -d " "); do
	checkinfile "$includefile"
    done
    for directory in $(grep '^\!includedir ' "$filename" | cut -f 2- -d " "); do
	for includefile in "$directory"/*.cnf; do
	    checkinfile "$includefile"
	done
    done
}

checkinfile $MYCNF

