#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

factory_settings['sslcertificates_default_levels'] = {
    'age': ( 90, 60 ),
    'warnalgo': [ 'md5WithRSAEncryption', 'sha1WithRSAEncryption' ],
    }

def sslcertificates_name(line):
    return line[0]

def inventory_sslcertificates(checkname, info):
    for line in info:
        yield sslcertificates_name(line), {}

def check_sslcertificates(item, params, info):
    if type(params) == tuple:
        # old config
        warn, crit = params
        warnalgos = factory_settings['sslcertificates_default_values']['algo']
        ignore = None
    else:
        warn, crit = params.get('age', (0, 0))
        warnalgos = params.get('warnalgo', [])
        ignore = params.get('ignore', None)

    for line in info:
        if item == sslcertificates_name(line):
            
            endtime = saveint(line[1])
            now = int(time.time())
            daysremaining = ( endtime - now ) / 60 / 60 / 24
            ignored = False

            algosign = '/'
            if len(line) > 2:
                algosign = line[2]
            if algosign[0] == '/':
                # old agent plugin
                algosign = ''
                subj = " ".join(line[2:])
            else:
                subj = " ".join(line[3:])
            yield 0, "Subject: %s" % subj

            if daysremaining < 0:
                infotext = "expired %d days ago on %s" % ( abs(daysremaining), time.strftime("%c", time.gmtime(endtime)))
            else:
                infotext = "expires in %d days on %s" % ( daysremaining, time.strftime("%c", time.gmtime(endtime)))
            if ignore and -daysremaining > ignore[0]:
                yield 0, infotext + ', ignored because "%s"' % ignore[1]
                ignored = True
            else:
                if daysremaining < crit:
                        yield 2, infotext
                elif daysremaining < warn:
                    yield 1, infotext
                else:
                    yield 0, infotext

            if algosign:
                infotext = "Signature Algorithm: %s" % algosign
                if not ignored and algosign in warnalgos:
                    yield 1, infotext
                else:
                    yield 0, infotext

check_info['sslcertificates'] = {
    'check_function':      check_sslcertificates,
    'service_description': "SSL Certificate in %s",
    'has_perfdata':        False,
    'inventory_function':  inventory_sslcertificates,
    'group':               'sslcertificates',
    'default_levels_variable' : "sslcertificates_default_levels",
}
