#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

factory_settings['sslcertificates_default_levels'] = {
    'age': ( 90, 60 ),
    'warnalgo': [ 'md5WithRSAEncryption', 'sha1WithRSAEncryption' ],
    }

def sslcertificates_name(line):
    return line[0]

def inventory_sslcertificates(checkname, info):
    for line in info:
        yield sslcertificates_name(line), {}

def check_sslcertificates(item, params, info):
    if type(params) == tuple:
        # old config
        warn, crit = params
        warnalgos = factory_settings['sslcertificates_default_values']['algo']
    else:
        warn, crit = params.get('age', (0, 0))
        warnalgos = params.get('warnalgo', [])

    for line in info:
        if item == sslcertificates_name(line):
            
            endtime = saveint(line[1])
            now = int(time.time())
            daysremaining = ( endtime - now ) / 60 / 60 / 24
            rc = 0

            algosign = '/'
            if len(line) > 2:
                algosign = line[2]
            if algosign[0] == '/':
                # old agent plugin
                algosign = ''
                subj = " ".join(line[2:])
            else:
                subj = " ".join(line[3:])
            infotext = "Subject: %s" % subj

            if algosign:
                infotext += "; Signature Algorithm: %s" % algosign
                if algosign in warnalgos:
                    rc = 1
                    infotext += "(!)"

            if daysremaining < 0:
                infotext += "; expired %d days ago on %s" % ( abs(daysremaining), time.strftime("%c", time.gmtime(endtime)))
            else:
                infotext += "; expires in %d days on %s" % ( daysremaining, time.strftime("%c", time.gmtime(endtime)))
            if daysremaining < crit:
                rc = 2
            elif daysremaining < warn:
                if rc < 2:
                    rc = 1
            return (rc, infotext)

check_info['sslcertificates'] = {
    'check_function':      check_sslcertificates,
    'service_description': "SSL Certificate in %s",
    'has_perfdata':        False,
    'inventory_function':  inventory_sslcertificates,
    'group':               'sslcertificates',
    'default_levels_variable' : "sslcertificates_default_levels",
}
