#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

import glob
import os
import os.path
import pwd

def fileowner(path):
    return pwd.getpwuid(os.stat(path).st_uid).pw_name

print '<<<filehandles>>>'
print 'global %s' % file('/proc/sys/fs/file-nr').read(),

mntns = os.readlink('/proc/self/ns/mnt')

for exe in glob.glob('/proc/*/exe'):
    try:
        bin = os.readlink(exe)
        if bin:
            piddir = os.path.dirname(exe)
            pid = os.path.basename(piddir)
            if pid.isdigit() and mntns == os.readlink(piddir + '/ns/mnt'):
                cmdline = piddir + '/cmdline'
                print "%s %d %s %s" % (pid,
                                       len(os.listdir(piddir + '/fd')),
                                       fileowner(cmdline),
                                       file(cmdline).read().replace('\0', ' ').strip())
    except OSError:
        pass
