#!/bin/bash

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

echo "<<<local>>>"

cat /proc/sys/fs/file-nr | while read allocated unused max; do

  warn=$(( $max * 80 / 100 ))
  crit=$(( $max * 90 / 100 ))

  echo "P Filehandles count=$allocated;$warn;$crit;0;$max Filehandles allocated, max is $max"

done

if [ -r $MK_CONFDIR/filehandles.cfg ]; then
    . $MK_CONFDIR/filehandles.cfg
    for exe in /proc/*/exe; do
	for proc in $PROCS; do
	    bin=$(readlink $exe)
	    if [ "$bin" = "$proc" ]; then
		pid=$(dirname $exe)
		echo $proc $(ls -1 $pid/fd | wc -l)
	    fi
	done
    done
fi
