#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_filehandles(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/local/icpraid", plugins_dir + "/../local/filehandles")

bakery_info["filehandles"] = {
    "bake_function" : bake_filehandles,
    "os"            : [ "linux", ],
}
