#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_ups_arguments(params):
    args = "-T"

    if 'hostname' in params:
        args += " -H %s" % quote_shell_string(params['hostname'])
    else:
        args += " -H $HOSTADDRESS$"

    args += " -u %s" % quote_shell_string(params['upsname'])

    if 'port' in params and params['port'] != 3493:
        args += " -p %d" % params['port']

    return args

def check_ups_description(params):
    return "UPS %s" % params['upsname']

active_check_info['ups'] = {
    "command_line": "$USER1$/check_ups $ARG1$",
    "argument_function": check_ups_arguments,
    "service_description": check_ups_description,
    "has_perfdata": True,
    }
