#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_ox_filestore(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/ox_filestore", plugins_dir + "/ox_filestore")
    if conf and 'username' in conf[0] and 'password' in conf[0]:
        f = file(conf_dir + "/ox_filestore", "w")
        f.write(agent_file_header)
        f.write("OX_ADMIN_MASTER=\"%s\"\n" % conf[0]['username'])
        f.write("OX_ADMIN_MASTER_PASSWORD=\"%s\"\n" % conf[0]['password'])

bakery_info["ox_filestore"] = {
    "bake_function" : bake_ox_filestore,
    "os"            : [ "linux", ],
    "matchtype"     : "all",
}
