#!/bin/bash

if [ -r /etc/os-release ]; then

    echo '<<<lsbrelease>>>'
    . /etc/os-release
    echo -e "Description:\t$PRETTY_NAME"
    echo -e "Release:\t$VERSION_ID"
    echo -e "Codename:\t$VERSION_CODENAME"

elif [ -r /etc/SuSE-release ]; then

    echo '<<<lsbrelease>>>'
    version=$(grep ^VERSION /etc/SuSE-release | cut -f 3 -d " ")
    patchlevel=$(grep ^PATCHLEVEL /etc/SuSE-release | cut -f 3 -d " ")
    if [ -n "$patchlevel" ]; then
        version="$version.$patchlevel"
    fi
    echo -e "Description:\tSUSE EOL"
    echo -e "Release:\t$version"

elif lsbrelease=$(which lsb_release); then

    echo '<<<lsbrelease>>>'
    $lsbrelease -a

fi
