#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_systemd(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/systemd", plugins_dir + "/systemd")

bakery_info["systemd"] = {
    "bake_function" : bake_systemd,
    "os"            : [ "linux", ],
}
