#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2024 Heinlein Consulting GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

from cmk.base.cee.plugins.bakery.bakery_api.v1 import quote_shell_string

def agent_ibm_hmc_arguments(params, hostname, ipaddress):
    args = []

    args.append('-H {}'.format(quote_shell_string(ipaddress or hostname)))

    args.append('-U {}'.format(quote_shell_string(params['username'])))

    if 'ssh_id' in params:
        args.append('-I {}'.format(params['ssh_id']))

    return ' '.join(args)

special_agent_info['ibm_hmc'] = agent_ibm_hmc_arguments
