#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_by_ssh_arguments(params):
    settings = params[1]

    if 'hostname' in settings:
        args = "-H %s" % quote_shell_string(settings['hostname'])
    else:
        args = "-H $HOSTADDRESS$"

    args += " -C \"%s\"" % params[0]

    if "port" in settings:
        args += " -p %d" % settings["port"]
        
    if "ip_version" in settings:
        if settings['ip_version'] == 'ipv4':
            args += ' -4'
        else:
            args += ' -6'

    if "timeout" in settings:
        args += ' -t %d' % settings["timeout"]

    if "logname" in settings:
        args += ' -l %s' % quote_shell_string(settings["logname"])

    if "identity" in settings:
        args += ' -i %s' % settings["identity"]

    return args

def check_by_ssh_description(params):
    settings = params[1]

    if 'description' in settings:
        return settings['description']
    
    return "check_by_ssh %s" % params[0]

active_check_info['by_ssh'] = {
    "command_line"        : '$USER1$/check_by_ssh $ARG1$',
    "argument_function"   : check_by_ssh_arguments,
    "service_description" : check_by_ssh_description ,
    "has_perfdata"        : True,
}


