#!/bin/bash

# check_mk check f. HP Smart Array Controller
#
# 01/2020 Robert Sander <r.sander@heinlein-support.de>
# 01/2011 Matthias Henze
# Lizenz: GPL v2

#
# https://github.com/HeinleinSupport/check_mk_extensions/tree/master/hpsa
#

# sample output
#
# hpssacli controller all show config
# 
# Smart Array P410i in Slot 0 (Embedded)    (sn: 50014380230B12F0)
# 
# 
# 
#    Internal Drive Cage at Port 1I, Box 1, OK
# 
# 
# 
#    Internal Drive Cage at Port 2I, Box 1, OK
# 
# 
#    Port Name: 1I
# 
#    Port Name: 2I
# 
#    Array A (SAS, Unused Space: 0  MB)
# 
#       logicaldrive 1 (558.73 GB, RAID 1+0, OK)
# 
#       physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SAS HDD, 300 GB, OK)
#       physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS HDD, 300 GB, OK)
#       physicaldrive 1I:1:3 (port 1I:box 1:bay 3, SAS HDD, 300 GB, OK)
#       physicaldrive 1I:1:4 (port 1I:box 1:bay 4, SAS HDD, 300 GB, OK)
# 
#    SEP (Vendor ID PMCSIERA, Model  SRC 8x6G) 250  (WWID: 50014380230B12FF)
# 

if [ -e  /proc/driver/cciss -o  -e /sys/bus/cciss -o -e /sys/bus/pci/drivers/hpsa ]; then

	# Do not check FC LUNs, speeds up processing
	export INFOMGR_BYPASS_NONSA=1

	for bin in ssacli hpssacli hpacucli; do
		RAID_CHECK_TOOL=$(which $bin 2> /dev/null)
		if [ -n "$RAID_CHECK_TOOL" ]; then
			break
		fi
	done

	echo '<<<hpsa_controller>>>'
	if [ -n "$RAID_CHECK_TOOL" ]; then
		$RAID_CHECK_TOOL controller all show config
	else
		echo "HP RAID check tool not installed."
	fi
fi
