#!/usr/bin/python 
# -*- encoding: utf-8; py-indent-offset: 4 -*- 
 
# 
# (c) 2013 Heinlein Support GmbH 
#          Robert Sander <r.sander@heinlein-support.de> 
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
 
def check_nfs_arguments(params):
    sharename, settings = params
    
    if 'hostname' in settings:
        args = "%s" % quote_shell_string(settings['hostname'])
    else: 
        args = "$HOSTADDRESS$"

    args += " %s" % quote_shell_string(sharename)
 
    if 'warning' in settings: 
        args += " %d%%" % settings['warning']
    else:
        args += " 20%"
 
    if 'critical' in settings:
        args += " %d%%" % settings['critical']
    else:
        args += " 10%"

    return args 
 
def check_nfs_description(params): 
    return "NFS %s" % params[0] 
 
active_check_info['nfs'] = { 
    "command_line": "$USER2$/check_nfs $ARG1$", 
    "argument_function": check_nfs_arguments, 
    "service_description": check_nfs_description, 
    "has_perfdata": True, 
    } 
