#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_dell_sc_encltemp(info):
    enclid = 1
    encltempid = 0
    res = []
    for line in info:
        if encltempid >= saveint(line[0]):
            enclid += 1
        line += [enclid]
        encltempid = saveint(line[0])
        res.append(line)
    return res

def item_dell_sc_encltemp(line):
    return "Encl %d Temp %s" % (line[4], line[0])

def inventory_dell_sc_encltemp(info):
    for line in info:
        yield item_dell_sc_encltemp(line), None

def check_dell_sc_encltemp(item, params, info):
    state = {
        1  : ('up', 0),
        2  : ('down', 2),
        3  : ('degraded', 1),
        }
    for line in info:
        if item_dell_sc_encltemp(line) == item:
            encltemp_state = state.get(saveint(line[1]), ('unknown', 3))
            temp_state, temp_text, perfdata = check_temperature(saveint(line[3]),
                                                                params,
                                                                'dell_sc_encltemp_%s' % item,
                                                                dev_status = encltemp_state[1],
                                                                dev_status_name = 'State is %s' % encltemp_state[0])
            info_text = "%s, Temperature is %s" % (
                line[2],
                temp_text,
            )
            return temp_state, info_text, perfdata

check_info["dell_sc_encltemp"] = {
    'parse_function'        : parse_dell_sc_encltemp,
    'check_function'        : check_dell_sc_encltemp,
    'inventory_function'    : inventory_dell_sc_encltemp,
    'service_description'   : 'Dell SC %s',
    'has_perfdata'          : True,
    'snmp_info'             : ('.1.3.6.1.4.1.674.11000.2000.500.1.2.23.1', [
        '2',    # scEnclTempNbr
        '3',    # scEnclTempStatus
        '4',    # scEnclTempLocation
        '5',    # scEnclTempCurrentC
        ] ),
    'snmp_scan_function'    : lambda oid: 'compellent' in oid('.1.3.6.1.2.1.1.1.0').lower() and oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0") != None,
    'includes'              : [ 'temperature.include' ],
    'group'                 : 'temperature',
}
