#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

from cmk.base.check_legacy_includes.fan import check_fan

def item_dell_sc_ctlrfan(line):
    ctlr, fan = line[0].split('.')
    return "Ctlr %s Fan %s" % (ctlr, fan)

def inventory_dell_sc_ctlrfan(info):
    for line in info:
        yield item_dell_sc_ctlrfan(line), None

def check_dell_sc_ctlrfan(item, params, info):
    state = {
        1  : ('up', 0),
        2  : ('down', 2),
        3  : ('degraded', 1),
        }
    if not params:
        params = {'lower' : (None, None)}
    for line in info:
        if item_dell_sc_ctlrfan(line) == item:
            res = check_fan(saveint(line[3]), params)
            ctlrfan_state = state.get(saveint(line[1]), ('unknown', 3))
            info_text = "%s, %s RPM, State is %s" % (
                line[2],
                line[3],
                ctlrfan_state[0],
            )
            return ctlrfan_state[1], info_text

check_info["dell_sc_ctlrfan"] = {
    'check_function'        : check_dell_sc_ctlrfan,
    'inventory_function'    : inventory_dell_sc_ctlrfan,
    'service_description'   : 'Dell SC %s',
    'has_perfdata'          : True,
    'snmp_info'             : ('.1.3.6.1.4.1.674.11000.2000.500.1.2.16.1', [
        OID_END,    # scCtlrFanNbr
        '3',    # scCtlrFanStatus
        '4',    # scCtlrFanName
        '5',    # scCtlrFanCurrentRpm
        ] ),
    'snmp_scan_function'    : lambda oid: 'compellent' in oid('.1.3.6.1.2.1.1.1.0').lower() and oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0"),
    'group'                 : "hw_fans",
}
