#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def inventory_dell_sc_volume(info):
    for line in info:
        yield line[0], None

def check_dell_sc_volume(item, params, info):
    state = {
        1  : ('up', 0),
        2  : ('down', 2),
        3  : ('degraded', 1),
        }
    for line in info:
        if line[0] == item:
            volume_state = state.get(saveint(line[1]), ('unknown', 3))
            info_text = "%s, State is %s" % (
                line[2],
                volume_state[0]
            )
            return volume_state[1], info_text

check_info["dell_sc_volume"] = {
    'check_function'        : check_dell_sc_volume,
    'inventory_function'    : inventory_dell_sc_volume,
    'service_description'   : 'Dell SC Volume %s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.11000.2000.500.1.2.26.1', [
        '2',    # scVolumeNbr
        '3',    # scVolumeStatus
        '4',    # scVolumeName
        ] ),
    'snmp_scan_function'    : lambda oid: 'compellent' in oid('.1.3.6.1.2.1.1.1.0').lower() and oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0") != None,
}
