#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def inventory_dell_sc_server(info):
    for line in info:
        yield line[0], None

def check_dell_sc_server(item, params, info):
    state = {
        1  : ('up', 0),
        2  : ('down', 2),
        3  : ('degraded', 1),
        }
    conn = {
        1  : 'up',
        2  : 'down',
        3  : 'partial',
        }
    for line in info:
        if line[0] == item:
            server_state = state.get(saveint(line[1]), ('unknown', 3))
            info_text = "%s, Number of Paths: %s, Connectivity %s, State is %s" % (
                line[2],
                line[4],
                conn.get(saveint(line[3]), line[3]),
                server_state[0]
            )
            return server_state[1], info_text

check_info["dell_sc_server"] = {
    'check_function'        : check_dell_sc_server,
    'inventory_function'    : inventory_dell_sc_server,
    'service_description'   : 'Dell SC Server %s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.11000.2000.500.1.2.27.1', [
        '2',    # scServerNbr
        '3',    # scServerStatus
        '4',    # scServerName
        '5',    # scServerCnctvy
        '6',    # scServerPathCount
        ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0") != None,
}
