#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (C) 2016 Heinlein Support GmbH
# Robert Sander <r.sander@heinlein-support.de>
#

from pickle import dumps
from base64 import b64encode
from cmk.utils import debug

def agent_perfcalc_arguments(servicespecs, hostname, ipaddress):
    params = {'servicespecs': servicespecs,
              'debug': debug.enabled()}

    cmd = []
    cmd += b64encode(dumps(params)).split('\n')

    return " ".join(cmd)

special_agent_info['perfcalc'] = agent_perfcalc_arguments
