#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_memcached(opsys, conf, conf_dir, plugins_dir):
    res = True
    if type(conf) == str and conf == '_no_deploy':
        res = False
    elif type(conf) == tuple:
        if conf[0] == "static":
            f = file(conf_dir + "/memcached.cfg", "w")
            f.write(agent_file_header)
            f.write("instances = %r\n" % conf[1])
    if res:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/mk_memcached", plugins_dir + "/mk_memcached")


bakery_info["memcached"] = {
    "bake_function" : bake_memcached,
    "os"            : [ "linux", ],
}
