#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_postconf(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/postconf", plugins_dir + "/postconf")

bakery_info["postconf"] = {
    "bake_function" : bake_postconf,
    "os"            : [ "linux", ],
}
