#!/usr/bin/env bash

wg=$(which wg)

if [ -x "$wg" ]; then
    echo '<<<wireguard:sep(9)>>>'
    for iface in $($wg show interfaces); do
        echo "[[$iface]]"
        $wg show $iface dump | tail -n +2 | cut -f1,3- -d'	'
    done

fi
