#!/bin/bash

wg=$(which wg)

if [ -x $wg ]; then
	echo '<<<wireguard:sep(9)>>>'
    wg show interfaces | while read iface ; do
        echo "[[$iface]]"
        wg show $iface dump | cut -f 3- -d '	'
    done
fi
