#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_gamatronic_bat_status(info):
    for line in info:
        yield line[0], {}

def check_gamatronic_bat_status(item, params, info):
    for line in info:
        if item == line[0]:
            if line[1] == "0":
                yield 0, "Charging"
            else:
                yield 1, "Not charging %s" % line[1]
            current = savefloat(line[2]) / 10.0
            yield 0, "Current is %0.2f A" % current, [ ( "current", current ) ]
            if line[3] == "0":
                yield 0, "Battery is OK"
            elif line[3] == "1":
                yield 2, "Battery has failed"
            elif line[3] == "2":
                yield 1, "Battery is low"
            else:
                yield 3, "Battery status unknown: %s" % line[3]
            if line[4] == "0":
                yield 0, "Fuse is OK"
            else:
                yield 2, "Fuse is bad"

check_info["gamatronic_bat_status"] = {
    "inventory_function"     : inventory_gamatronic_bat_status,
    "check_function"         : check_gamatronic_bat_status,
    "service_description"    : "Battery Status %s",
    "has_perfdata"           : True,
    "snmp_info"              : (".1.3.6.1.4.1.6050.1.2.26.1", [
                                        1, # psBatteryIndex
                                        2, # psBatteryCurrentDirection
                                        3, # psBatteryCurrent
                                        6, # psBatteryStatus
                                        7, # psBatteryFuseStatus
                               ]),
    "snmp_scan_function"     : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.6050.5",
}
