#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

factory_settings["gamatronic_bat_temp_default"] = {
    "levels"    : (40, 50),
}

def inventory_gamatronic_bat_temp(info):
    for line in info:
        yield line[0], {}

def check_gamatronic_bat_temp(item, params, info):
    for line in info:
        if item == line[0]:
            factor = 1.0
            if saveint(line[1]) == 1:
                factor = -1.0
            return check_temperature(savefloat(line[1]) * factor, params, "ups_bat_temp_%s" % item)

check_info["gamatronic_bat_temp"] = {
    "inventory_function"     : inventory_gamatronic_bat_temp,
    "check_function"         : check_gamatronic_bat_temp,
    "service_description"    : "Temperature Battery %s",
    "has_perfdata"           : True,
    "default_levels_variable": "gamatronic_bat_temp_default",
    "group"                  : "temperature",
    "snmp_info"              : (".1.3.6.1.4.1.6050.1.2.26.1", [
                                        1, # psBatteryIndex
                                        4, # psBatteryTemperatureSign
                                        5, # psBatteryTemperature
                               ]),
    "snmp_scan_function"     : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.6050.5",
    "includes"               : [ "temperature.include" ],
}
