#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_gamatronic_info(info):
    if len(info) == 1 and len(info[0]) == 6:
        yield None, None

def check_gamatronic_info(_no_item, _no_params, info):
    if len(info) == 1 and len(info[0]) == 6:
        return 0, "%s %s, Battery: %s %s, Controller: %s, Serial: %s" % (info[0][0], info[0][1], info[0][2], info[0][3], info[0][4], info[0][5])

check_info["gamatronic_info"] = {
    "inventory_function"     : inventory_gamatronic_info,
    "check_function"         : check_gamatronic_info,
    "service_description"    : "Gamatronic Info",
    "has_perfdata"           : False,
    "snmp_info"              : (".1.3.6.1.4.1.6050.1.1", [
                                    2.0, # psUnitManufacture
                                    1.0, # psUnitSysName
                                    3.0, # psUnitBatteryType
                                    4.0, # psUnitPSType
                                    5.0, # psUnitControllerType
                                    8.0, # psUnitSerialNumber
                               ]),
    "snmp_scan_function"     : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.6050.5",
    "includes"               : [ "temperature.include" ],
}
