#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_gamatronic_out_phase(info):
    parsed = {}
    for line in info:
        parsed[line[0]] = { 'voltage': saveint(line[1]),
                            'current': saveint(line[2]),
                            'power': saveint(line[3]) * 100,
                            'appower': saveint(line[4]) * 100,
                            }
    return parsed

def inventory_gamatronic_out_phase(parsed):
    for item in parsed:
        yield item, {}

check_info["gamatronic_out_phase"] = {
    "parse_function"         : parse_gamatronic_out_phase,
    "inventory_function"     : inventory_gamatronic_out_phase,
    "check_function"         : check_elphase,
    "service_description"    : "UPS Output Phase %s",
    "has_perfdata"           : True,
    "group"                  : "ups_outphase",
    "snmp_info"              : (".1.3.6.1.4.1.6050.5.5.1.1", [
                                        1,
                                        2, # InputVoltage
                                        3, # InputCurrent
                                        4, # InputAcPower
                                        5, # InputApPower
                               ]),
    "snmp_scan_function"     : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.6050.5",
    "includes"               : [ "elphase.include" ],
}
