#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_dynamics_crm_storage_instance(info):
    for line in info:
        if line[0] == 'storageusedbycrminstances':
            yield line[2], {}

def check_dynamics_crm_storage_instance(item, params, info):
    for line in info:
        if line[0] == 'storageusedbycrminstances' and item == line[2]:
            storage_used = savefloat(line[1]) * 1048576.0
            yield 0, '%s used' % get_bytes_human_readable(storage_used), [ ( 'storage_used', storage_used ) ]
    

check_info["dynamics_crm_storage_instance"] = {
    'check_function'         : check_dynamics_crm_storage_instance,
    'inventory_function'     : inventory_dynamics_crm_storage_instance,
    'service_description'    : 'Dynamics CRM Instance %s',
    'has_perfdata'           : True,
}
