#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

dynamics_crm_waiting_jobs_default_levels = (100, 500)

def inventory_dynamics_crm_waiting_jobs(info):
    if cmk.debug.enabled():
        pprint.pprint(info)
    if len(info) == 1 and len(info[0]) == 1:
        yield (None, 'dynamics_crm_waiting_jobs_default_levels')

def check_dynamics_crm_waiting_jobs(_no_item, params, info):
    if cmk.debug.enabled():
        pprint.pprint(params)
        pprint.pprint(info)
    if len(info) == 1 and len(info[0]) == 1:
        waitingjobs = saveint(info[0][0])
        if type(params) == tuple:
            warn, crit = params
        else:
            warn, crit = None, None
        state, text, perf = check_levels(waitingjobs, 'waitingjobs', params)
        yield state, '%d waiting jobs%s' % (waitingjobs, text), [('waitingjobs', waitingjobs, warn, crit)] + perf

check_info["dynamics_crm_waiting_jobs"] = {
    'check_function'        : check_dynamics_crm_waiting_jobs,
    'inventory_function'    : inventory_dynamics_crm_waiting_jobs,
    'service_description'   : 'Dynamics CRM Waiting Jobs',
    'has_perfdata'          : True,
    'group'                 : 'dynamics_crm_waiting_jobs',
}
