#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_dynamics_crm_orb_transferlog(info):
    if cmk.debug.enabled():
        pprint.pprint(info)
    if len(info):
        yield None, {}

def check_dynamics_crm_orb_transferlog(_no_item, params, info):
    if cmk.debug.enabled():
        pprint.pprint(params)
        pprint.pprint(info)
    for line in info:
        count = saveint(line[0])
        yield 0, '%d responses in state %s' % ( count, " ".join(line[1:]) ), [ ( 'count', count ) ]

check_info["dynamics_crm_orb_transferlog"] = {
    'check_function'        : check_dynamics_crm_orb_transferlog,
    'inventory_function'    : inventory_dynamics_crm_orb_transferlog,
    'service_description'   : 'Dynamics CRM ORB Transferlog',
    'has_perfdata'          : True,
}
