#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

dynamics_crm_api_success_rate_default_levels = (99, 98)

def inventory_dynamics_crm_api_success_rate(info):
    if cmk.debug.enabled():
        pprint.pprint(info)
    if len(info) == 1 and info[0][0] == 'apipassrate':
        yield (None, 'dynamics_crm_api_success_rate_default_levels')

def check_dynamics_crm_api_success_rate(_no_item, params, info):
    if cmk.debug.enabled():
        pprint.pprint(params)
        pprint.pprint(info)
    if len(info) == 1 and info[0][0] == 'apipassrate':
        apipassrate = savefloat(info[0][1])
        warn, crit = params
        state = 0
        if apipassrate < crit:
            state = 2
        elif apipassrate < warn:
            state = 1
        yield state, '%0.1f%% successful API requests' % apipassrate, [('health', apipassrate, warn, crit)]

check_info["dynamics_crm_api_success_rate"] = {
    'check_function'        : check_dynamics_crm_api_success_rate,
    'inventory_function'    : inventory_dynamics_crm_api_success_rate,
    'service_description'   : 'Dynamics CRM API Success Rate',
    'has_perfdata'          : True,
    'group'                 : 'dynamics_crm_api_success_rate',
}
