#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_dynamics_crm_active_users(info):
    if len(info) == 1 and info[0][0] == 'totalactiveusers':
        yield (None, {})

def check_dynamics_crm_active_users(_no_item, params, info):
    if len(info) == 1 and info[0][0] == 'totalactiveusers':
        activeusers = savefloat(info[0][1])
        yield 0, '%0.2f active users' % activeusers, [('current_users', activeusers)]

check_info["dynamics_crm_active_users"] = {
    'check_function'        : check_dynamics_crm_active_users,
    'inventory_function'    : inventory_dynamics_crm_active_users,
    'service_description'   : 'Dynamics CRM Active Users',
    'has_perfdata'          : True,
}
