#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_dynamics_crm_storage_tenant(info):
    if len(info) % 2 == 0:
        yield 'Total', {} 

def check_dynamics_crm_storage_tenant(item, params, info):
    if len(info) % 2 == 0:
        storage = {'storageusedbyorg': 0.0, 'storageallocatedtoorg': 0.0}
        for line in info:
            storage[line[0]] += savefloat(line[1])
        size_mb = storage['storageallocatedtoorg']
        avail_mb = size_mb - storage['storageusedbyorg']
        yield df_check_filesystem_list(item, params, [ (item, size_mb, avail_mb, 0) ])

check_info["dynamics_crm_storage_tenant"] = {
    'check_function'         : check_dynamics_crm_storage_tenant,
    'inventory_function'     : inventory_dynamics_crm_storage_tenant,
    'service_description'    : 'Dynamics CRM Storage %s',
    'has_perfdata'           : True,
    'group'                  : 'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
    'includes'               : [ 'df.include' ],
}
