#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


def check_ups_out_source(_no_item, _no_params, info):
    map_source = {
        "1": (1, "Other"),
        "2": (2, "None"),
        "3": (0, "Normal"),
        "4": (1, "Bypass"),
        "5": (2, "Battery"),
        "6": (1, "Booster"),
        "7": (1, "Reducer"),
    }

    state, text = map_source.get(info[0][0], (3, "Unknown"))

    return state, "Output source is %s" % text

check_info['ups_out_source'] = {
    "inventory_function": discover_single,
    "check_function": check_ups_out_source,
    "service_description": "OUT source",
    "has_perfdata": False,
    "snmp_info": (".1.3.6.1.2.1.33.1.4", ["1.0"]),
    "snmp_scan_function": ups_generic_scan_function,
    "includes": ["ups_generic.include"],
}
