#!/bin/bash

echo '<<<local>>>'

awk '/aufs/ { print $2;}' < /proc/mounts | sort -u | while read dir; do
    msg=$(/bin/ls "$dir"/* 2>&1  1> /dev/null)
    res=$?
    if [ -z "$msg" ]; then
        msg="Overlay filesystem OK"
    fi
    echo $res aufs_$(echo $dir | tr " " "_") - $msg $tmpfile
done
