#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2014 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_ceph(info):
    inventory = []
    if len(info) > 0:
        inventory.append(( None, [] ))
    return inventory

def check_ceph(item, params, info):
    rc = 0
    perfdata = []
    text = []
    factor = { 'PB': 1125899906842624,
               'TB': 1099511627776,
               'GB': 1073741824,
               'MB': 1048576,
               'KB': 1024,
             }
    for line in info:
        if line[0] == 'cluster':
            text.append('Cluster %s' % line[1])
        if line[0] == 'health':
            text.append(' '.join(line[1:]))
            if line[1] != 'HEALTH_OK':
                rc = 2
        if len(line) > 7 and line[2] == 'used,':
            text.append(' '.join(line))
            used = saveint(line[0]) * factor[line[1]]
            size = saveint(line[6]) * factor[line[7]]
            warn = 0.8 * size
            crit = 0.9 * size
            perfdata.append(("Used", "%dB" % used, warn, crit, 0, size))
            if rc == 0:
                if used > crit:
                    rc = 2
                elif used > warn:
                    rc = 1
    if len(text) == 0:
        rc = 3
        text = ['Unable to find status information.']
    return (rc, '; '.join(text), perfdata)

check_info["ceph"] = {
    'check_function'        : check_ceph,
    'inventory_function'    : inventory_ceph,
    'service_description'   : 'Ceph',
    'has_perfdata'          : True,
}

