#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def item_name(line):
	return line[0] + "_" + line[1] + "_" + line[2]

def inventory_dirvish(info):
	inventory = []
	for line in info:
		inventory.append( ( item_name(line), "", None ) )
	return inventory

def check_dirvish(item, params, info):
	for line in info:
		if item == item_name(line):
			image = line[4]
			status = line[5]
			if status == "success":
				return (0, "OK - Backup %s completed" % image)
			elif status == "running":
				return (0, "OK - Backup %s running" % image)
			elif status == "warning":
				return (1, "WARNING - Backup %s unreliable" % image)
			elif status == "unknown":
				return (3, "UNKNOWN - Backup %s status unknown" % image)
			else:
				return (2, "CRITICAL - Backup %s failed" % image)
	return (3, "UNKNOWN - Backup %s not found" % item)

check_info["dirvish"] = {
    'check_function'        : check_dirvish,
    'inventory_function'    : inventory_dirvish,
    'service_description'   : 'Backup status %s',
    'has_perfdata'          : False,
}


		
