#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_lsbrelease(opsys, conf, conf_dir, plugins_dir):
    if "interval" in conf:
        target_dir = plugins_dir + "/%d" % conf["interval"] # Interval for async execution
        if not os.path.exists(target_dir):
            os.makedirs(target_dir)
    else:
        target_dir = plugins_dir
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/lsbrelease", target_dir + "/lsbrelease")

bakery_info["lsbrelease"] = {
    "bake_function" : bake_lsbrelease,
    "os"            : [ "linux", ],
}
