#!/bin/bash

# (c) 2014 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

if [ -x /usr/bin/ceph ]; then
  if [ $(ceph version | cut -f 3 -d " " | cut -f 1 -d .) -lt 10 ]; then
    echo '<<<ceph>>>'
    /usr/bin/ceph -s
    echo '<<<cephpools>>>'
    /usr/bin/ceph df
  else
    echo '<<<cephstatus>>>'
    /usr/bin/ceph -f json status

    echo '<<<cephdf>>>'
    /usr/bin/ceph -f json df detail

    echo '<<<cephosd>>>'
    echo '{ "df": '
    /usr/bin/ceph -f json osd df
    echo ', "perf": '
    /usr/bin/ceph -f json osd perf
    echo '}'
  fi
fi
