#!/bin/bash

# (c) 2014 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

if [ -x /usr/bin/ceph ]; then

  INT=30

  if [ $(ceph version | cut -f 3 -d " " | cut -f 1 -d .) -lt 10 ]; then
    echo "<<<ceph:cached($(date +%s),$INT)>>>"
    /usr/bin/ceph -s
    echo "<<<cephpools:cached($(date +%s),$INT)>>>"
    /usr/bin/ceph df
  else
    echo "<<<cephstatus:cached($(date +%s),$INT)>>>"
    /usr/bin/ceph -f json status

    echo "<<<cephdf:cached($(date +%s),$INT)>>>"
    /usr/bin/ceph -f json df detail

    echo "<<<cephosd:cached($(date +%s),$INT)>>>"
    echo '{ "df": '
    /usr/bin/ceph -f json osd df
    echo ', "perf": '
    /usr/bin/ceph -f json osd perf
    echo ', "nodes": '
    /usr/bin/ceph -f json node ls osd
    echo "}"

    jq=$(which jq)
    echo "<<<cephosdbluefs:cached($(date +%s),$INT)>>>"
    echo '{'
    for i in /var/lib/ceph/osd/*/type; do
      if [ "$(cat $i)" = "bluestore" ]; then
        dir=$(dirname $i)
        osdid=$(cat $dir/whoami)
        if [ -n "$osdid" ]; then
          echo " \"$osdid\": "
          if [ -n "$jq" ]; then
             echo '{ "bluefs": '
             ceph daemon osd.$osdid perf dump | $jq .bluefs
             echo '},'
           else
             ceph daemon osd.$osdid perf dump
           fi
         fi
      fi
    done
    echo '"end":{}}'
  fi
fi
