#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_dovereplstat(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/dovereplstat", plugins_dir + "/dovereplstat")

bakery_info["dovereplstat"] = {
    "bake_function" : bake_dovereplstat,
    "os"            : [ "linux", ],
}
