#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_hpsa_array(checkname, info):
    return [ ( line[0], None ) for line in info ]

def check_hpsa_array(item, params, info):
    for line in info:
        if item == line[0]:
            if len(line) > 2:
                infotext = " ".join(line[2:])
            else:
                infotext = " ".join(line)
            if len(line) > 1:
                if line[1] == 'OK' or line[1] == 'Used':
                    rc = 0
                else:
                    rc = 2
                    infotext = " ".join(line)
            else:
                rc = 3
                infotext = "Unknown output from agent plugin: " + infotext
            return (rc, infotext)
    return (3, "Unknown Array: %s" % item)

check_info['hpsa_array'] = {
    'check_function':      check_hpsa_array,
    'service_description': "HP RAID Array %s",
    'has_perfdata':        False,
    'inventory_function':  inventory_hpsa_array,
}

