#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_usp_ses(info):
    for line in info:
        yield line[1], {}

def check_usp_ses(item, params, info):
    for line in info:
        if item == line[1]:
            connections = saveint(line[2])
            requests = savefloat(line[3])
            activeusers = saveint(line[4])
            reqtime = savefloat(line[5])
            yield 0, "%d client connections" % connections, [('connections', connections)]
            yield 0, "%.2f requests per second" % requests, [('requests_per_second', requests)]
            yield 0, "%d active users" % activeusers, [('current_users', activeusers)]
            yield 0, "average request time: %s" % get_age_human_readable(reqtime), [('average_request_time', reqtime)]

check_info["usp_ses"] = {
    "inventory_function"      : inventory_usp_ses,
    "check_function"          : check_usp_ses,
    "service_description"     : "USP SES %s",
    "has_perfdata"            : True,
    "snmp_info"               : (".1.3.6.1.4.1.26458.5911.100.2.2.1", [
                                        1, # vhostIndex
                                        2, # vhostName
                                        3, # vhostClientConnections
                                        4, # vhostRequestPerSecond
                                        5, # vhostActiveUsers
                                        6, # vhostAvgRequestTime
                               ]),
    "snmp_scan_function"      : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.26458.7419",
}
