#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_msexch_database_size(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/windows/plugins/msexch_database_size.ps1", plugins_dir + "/msexch_database_size.ps1")

bakery_info["msexch_database_size"] = {
    "bake_function" : bake_msexch_database_size,
    "os"            : [ "windows", ],
}

