#!/usr/bin/env python3
# WebSMScom
# Bulk: no

import os, requests, sys, json, logging
from cmk.notification_plugins import utils

logfile = os.path.join(os.environ.get('OMD_ROOT'), "var", "log", "websmscom.log") # type: ignore

logger = logging.getLogger("WebSMScom")
logging.basicConfig(
    filename=logfile,
    encoding="utf-8",
    level=logging.INFO,
    format="%(asctime)s;%(message)s"
)

def send_it(pager, art, message, token):
    post = {
        "maxSmsPerMessage"    : 0,
        "recipientAddressList": [ pager ],
        "messageType"         : art,
        "messageContent"      : message,
    }

    url = f"https://api.websms.com/rest/smsmessaging/text"
    headers = {
        "Content-type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {token}"
    }

    req = requests.post(url, data=json.dumps(post), headers=headers)
    check = check_response(req)

    if check["status_code"] != 200:
        print(str(check["text"]["statusCode"])+"\nAPI Error: "+check["text"]["statusMessage"]+" | "+str(check["text"]["statusCode"]))
        sys.exit(1)

    return check

def check_response(response):
    answer = {
        "status_code" : response.status_code,
        "reason": response.reason,
        "text" : {},
    }
 
    if response.text:
        check = json.loads(response.text)
        if "error" in check:
            answer["text"] = { "statusCode" : response, "statusMessage" : check["error_description"] }
        elif response.text:
            answer["text"] = { "statusCode" : check["statusCode"], "statusMessage" : check["statusMessage"] }
 
    if not response.text:
        answer["text"] = { "statusCode" : response.status_code, "statusMessage" : response.reason }
 
    return answer

def get_sms_message_from_context(raw_context: utils.PluginNotificationContext, max_len: int = 160) -> str:
    notification_type = raw_context["NOTIFICATIONTYPE"]
    message = raw_context["HOSTNAME"] + " "
    if raw_context["WHAT"] == "SERVICE":
        if notification_type in ["PROBLEM", "RECOVERY"]:
            message += raw_context["SERVICESTATE"] + " "
            avail_len = max_len - len(message)
            message += raw_context["SERVICEDESC"][:avail_len] + " "
            avail_len = max_len - len(message)
            message += raw_context["SERVICEOUTPUT"][:avail_len]
        else:
            message += raw_context["SERVICEDESC"]
    else:
        if notification_type in ["PROBLEM", "RECOVERY"]:
            message += "is " + raw_context["HOSTSTATE"]

    if notification_type.startswith("FLAP"):
        if "START" in notification_type:
            message += " Started Flapping"
        else:
            message += " Stopped Flapping"

    elif notification_type.startswith("DOWNTIME"):
        what = notification_type[8:].title()
        message += " Downtime " + what
        message += " " + raw_context["NOTIFICATIONCOMMENT"]

    elif notification_type == "ACKNOWLEDGEMENT":
        message += " Acknowledged"
        message += " " + raw_context["NOTIFICATIONCOMMENT"]

    elif notification_type == "CUSTOM":
        message += " Custom Notification"
        message += " " + raw_context["NOTIFICATIONCOMMENT"]

    return message

def main():
    context = utils.collect_context()
    
    token = None
    
    if context["PARAMETER_TOKEN_1"] == "cmk_postprocessed":
        if context["PARAMETER_TOKEN_2"] == "stored_password":
            token = utils.retrieve_from_passwordstore("store " + context["PARAMETER_TOKEN_3_1"])
        if context["PARAMETER_TOKEN_2"] == "explicit_password":
            token = context["PARAMETER_TOKEN_3_2"]
            
    if not token:
        print("No Token configured.")
        sys.exit(2)
    
    # Ignore contacts without pager number
    try:
        pager = context["CONTACTPAGER"]
        if not pager:
            print("No pager configured")
            sys.exit(2)
    except KeyError:
        print("No pager configured")
        sys.exit(2)

    if pager[:3] != "+49":
        print("Die Rufnummer muss mit +49 beginnen")
        sys.exit(2)

    try:
        art = context["PARAMETER_ART"]
    except:
        print("No message type set (text or voice)")
        sys.exit(2)

    datetime = "\n" + context["SHORTDATETIME"]
    message = get_sms_message_from_context(context, 320 - len(datetime))

    if art == "complete":
        req=send_it(pager, "default", message + datetime, token)
        logger.info(f"{pager};{context['CONTACTNAME']};default;{message};{req['text']['statusCode']}")
        req=send_it(pager, "voice", message + datetime, token)
        logger.info(f"{pager};{context['CONTACTNAME']};voice;{message};{req['text']['statusCode']}")
    else:
        req=send_it(pager, art, message + datetime, token)
        logger.info(f"{pager};{context['CONTACTNAME']};{art};{message};{req['text']['statusCode']}")

    if art == "complete":
        print("Notification successful: WebSMS.com Text and Voice")
    elif art == "default":
        print("Notification successful: WebSMS.com Text")
    else:
        print("Notification successful: WebSMS.com Voice")

if __name__ == "__main__":
    main()

# -*- encoding: utf-8; py-indent-offset: 4 -*-
