#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_hpsa(opsys, conf, conf_dir, plugins_dir):
    if conf:
        target_dir = plugins_dir
        if type(conf) == dict and 'interval' in conf:
            target_dir = plugins_dir + "/%d" % conf["interval"]
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/hpsa", target_dir + "/hpsa")

bakery_info["hpsa"] = {
    "bake_function" : bake_hpsa,
    "os"            : [ "linux", ],
}
