#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_mh_hpsa(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/mh_hpsa", plugins_dir + "/mh_hpsa")

bakery_info["mh_hpsa"] = {
    "bake_function" : bake_mh_hpsa,
    "os"            : [ "linux", ],
}
