#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 vim: set ft=python:-*-

# (c) 2020 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# {'DatabaseSize': '3.625 GB (3,892,314,112 bytes)', 'Name': 'deactivated_Users'}
# {'DatabaseSize': '1.003 TB (1,102,732,853,248 bytes)', 'Name': 'active_Users'}
# {'DatabaseSize': '41.63 GB (44,694,503,424 bytes)', 'Name': 'Shared_Mailbox'}

info = [[u'"Name"', u'"DatabaseSize"'],
 [u'"deactivated_Users"', u'"3.625 GB (3,892,314,112 bytes)"'],
 [u'"active_Users"', u'"1.003 TB (1,102,732,853,248 bytes)"'],
 [u'"Shared_Mailbox"', u'"41.63 GB (44,694,503,424 bytes)"']]


def parse_msexch_database_size(info):
    parsed = {}

    for line in info:
        name = line[0].strip('"')
        if name == u'Name':
            continue
        sizestr = line[1].strip('"')
        size = int(sizestr.split('(')[1].split(' ')[0].replace(',', ''))
        parsed[name] = size

    return parsed


def inventory_msexch_database_size(parsed):
    for instance, data in parsed.iteritems():
        yield instance, {}


def check_msexch_database_size(item, params, parsed):
    size = parsed.get(item)
    if size is None:
        return

    yield check_levels(size,
                       'database_size',
                       params,
                       human_readable_func=get_filesize_human_readable,
                       infoname="Size")

check_info['msexch_database_size'] = {
    'inventory_function': inventory_msexch_database_size,
    'check_function': check_msexch_database_size,
    'parse_function': parse_msexch_database_size,
    'has_perfdata': True,
    'service_description': "Exchange Database Size %s",
    "group": "msexch_database_size",
}
