#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_proxmox_provisioned(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/proxmox_provisioned", plugins_dir + "/proxmox_provisioned")

bakery_info["proxmox_provisioned"] = {
    "bake_function" : bake_proxmox_provisioned,
    "os"            : [ "linux", ],
}
