#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_proxmox_provisioned(opsys, conf, conf_dir, plugins_dir):
    if conf:
        target_dir = plugins_dir

        # Handle the optional async/interval flag
        if "interval" in conf:
            target_dir = plugins_dir + "/%d" % conf["interval"] # Interval for async execution
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

        # Deploy the agent plugin
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/proxmox_provisioned", target_dir + "/proxmox_provisioned")

bakery_info["proxmox_provisioned"] = {
    "bake_function" : bake_proxmox_provisioned,
    "os"            : [ "linux", ],
}
