#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def bake_dir_size_ls(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(local_agents_dir + "/plugins/dir_size_ls", plugins_dir + "/dir_size_ls")
    f = file(conf_dir + "/dir_size_ls.cfg", "w")
    f.write(agent_file_header)

    dirs = []

    for entry in conf:
        dirs.extend(entry["directories"])

    f.write("%s\n" % "\n".join(sorted(dirs)))

bakery_info["dir_size_ls"] = {
    "bake_function" : bake_dir_size_ls,
    "os"            : [ "linux", ],
    "matchtype"     : "all",
}
