#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_jenkins(opsys, conf, conf_dir, plugins_dir):
    if conf:
        f = file(conf_dir + "/jenkins.cfg", "w")
        f.write(agent_file_header)
        f.write("params = %r\n" % conf)

        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/jenkins", plugins_dir + "/jenkins")

bakery_info["jenkins"] = {
    "bake_function" : bake_jenkins,
    "os"            : [ "linux", ],
}
