#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

def check_ups_arguments(params):
    args = "-T"

    if 'hostname' in params:
        args += " -H %s" % quote_shell_string(params['hostname'])
    else:
        args += " -H $HOSTADDRESS$"

    args += " -u %s" % quote_shell_string(params['upsname'])

    if 'port' in params and params['port'] != 3493:
        args += " -p %d" % params['port']

    return args

def check_ups_description(params):
    return "UPS %s" % params['upsname']

active_check_info['ups'] = {
    "command_line": "$USER1$/check_ups $ARG1$",
    "argument_function": check_ups_arguments,
    "service_description": check_ups_description,
    "has_perfdata": True,
    }
