#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

pvs_default_values = ( 90, 95 )

def pvs_name(line):
    return line[0]

def inventory_pvs(checkname, info):
    inventory = []
    for line in info:
        inventory.append( ( pvs_name(line), "pvs_default_values", None ) )
    return inventory

def check_pvs(item, params, info):
    try:
        warn, crit = params
    except TypeError:
        warn, crit = pvs_default_values
    for line in info:
        if item == pvs_name(line):
            total = int(line[4])
            free = int(line[5])
            percfull = 100.0 - free * 100.0 / total
            perfdata = [
                         ( "free", free, total * ( 1.0 - warn / 100.0 ), total * ( 1.0 - crit / 100.0 ), 0.0, total ),
                         ( "perc_full", percfull, warn, crit, 0.0, 100.0),
                       ]
            if percfull > crit:
                return (2, "PV %0.2f%% full" % percfull, perfdata)
            elif percfull > warn:
                return (1, "PV nearly full: %0.2f%%" % percfull, perfdata)
            return (0, "PV ready: %0.2f%%" % percfull, perfdata)
    return (3, "PV %s not found" % item, [])

check_info['pvs'] = ( check_pvs, "PV %s", 1, inventory_pvs )
