#!/bin/bash

# (c) 2022 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

ps aux | grep openvpn | sed -n  's/^.*--daemon \(\S*\) --status \(\S*\) .*$/\1 \2/p' | while read insta status; do
  if [ -r "$status" ]; then
    if grep -q "CLIENT LIST" "$status"; then
      echo '<<<openvpn_clients:sep(44)>>>'
      echo "[[$insta]]"
      sed -n -e '/CLIENT LIST/,/ROUTING TABLE/p' < $status | sed -e 1,3d -e '$d'
    fi
  fi
done

