#!/bin/bash

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

max=$(cat /proc/sys/net/nf_conntrack_max)
cur=$(cat /proc/sys/net/netfilter/nf_conntrack_count)
war=$(($max * 80 / 100))
cri=$(($max * 90 / 100))

echo "P CONNTRACK count=$cur;$war;$cri;0;$max connections maximum is $max"

