#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_rbl_check(checkname, info):
    inventory = set()
    for line in info:
	inventory.add((line[0], None))
    return list(inventory)

def check_rbl_check(item, params, info):
    res = []
    for line in info:
	if line[0] == item:
	    if line[2] == 'found':
		res.append('found in %s' % line[1])
    if res:
	return(2, ", ".join(res))
    return(0, "not found in any RBL")

check_info["rbl_check"] = {
    'check_function': check_rbl_check,
    'inventory_function': inventory_rbl_check,
    'service_description': 'RBL Check %s',
    'has_perfdata': False,
}
