#!/bin/bash

uname=$(which uname)

if [ -x "$uname" ]; then

    echo '<<<uname>>>'
    echo -n "kernel-name "; uname -s
    echo -n "kernel-release "; uname -r
    echo -n "kernel-version "; uname -v
    echo -n "machine "; uname -m
    echo -n "processor "; uname -p
    echo -n "hardware "; uname -i
    echo -n "opsys "; uname -o

fi

