#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_ceph(opsys, conf, conf_dir, plugins_dir):
    if conf:
        target_dir = plugins_dir + "/30"
        if not os.path.exists(target_dir):
            os.makedirs(target_dir)
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/ceph", target_dir + "/ceph")

bakery_info["ceph"] = {
    "bake_function" : bake_ceph,
    "os"            : [ "linux", ],
}
