#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_ceph(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/ceph", plugins_dir + "/ceph")

bakery_info["ceph"] = {
    "bake_function" : bake_ceph,
    "os"            : [ "linux", ],
}
