#!/bin/bash

if [ -x /opt/zimbra/bin/postconf ] ; then
    echo '<<<postfix_mailq>>>'
    postfix_queue_dir=$(/opt/zimbra/bin/postconf -h queue_directory)
    postfix_count=$(find $postfix_queue_dir/deferred -type f | wc -l)
    postfix_size=$(du -ks $postfix_queue_dir/deferred | awk '{print $1 }')
    if [ $postfix_count -gt 0 ]
    then
       echo -- $postfix_size Kbytes in $postfix_count Requests.
    else
       echo Mail queue is empty
    fi
fi
