#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_mongodb_arguments(params):

    print params

    action, settings, maxlag, mappedmem, ssl, replicaset, perfdata = params

    if 'hostname' in settings:
        args = "-H %s" % quote_shell_string(settings['hostname'])
    else:
        args = "-H $HOSTADDRESS$"

    args += " --action=%s" % action

    for setting in ['port', 'user', 'pass', 'warning', 'critical', 'querytype', 'collection', 'time']:
        if setting in settings:
            args += " --%s=%s" % (setting, settings[setting])

    if 'database' in settings and settings['database']:
        if type(settings['database']) == type(True):
            args += " --all-databases"
        else:
            args += " --database=%s" % settings['database']

    if maxlag:
        args += " --max-lag"

    if mappedmem:
        args += " --mapped-memory"

    if ssl:
        args += " --ssl"

    if replicaset:
        args += " --replicaset"

    if perfdata:
        args += " --perf-data"

    return args

def check_mongodb_description(params):
    description = "MongoDB"

    action, settings, maxlag, mappedmem, ssl, replicaset, perfdata = params

    description += " %s port %s" % (action, settings['port'])

    return description

def check_mongodb_perfdata(params):
    return params[6]

active_check_info['mongodb'] = {
    "command_line"        : '$USER2$/check_mongodb.py $ARG1$',
    "argument_function"   : check_mongodb_arguments,
    "service_description" : check_mongodb_description,
    "has_perfdata"        : check_mongodb_perfdata,
}


