#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_heinlein_mysql(opsys, conf, conf_dir, plugins_dir):
    target_dir = plugins_dir

    # Handle the optional async/interval flag
    if "interval" in conf:
        target_dir = plugins_dir + "/%d" % conf["interval"] # Interval for async execution
        if not os.path.exists(target_dir):
            os.makedirs(target_dir)

    # Deploy the agent plugin
    shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/heinlein_mysql", target_dir + "/heinlein_mysql")

    # Create the agent configuration
    content = agent_file_header
    if "credentials" in conf:
        content += "[client]\n" \
                   "user=%s\n" \
                   "password=\"%s\"\n" % conf['credentials']
    if "socket" in conf:
        content += "socket=%s\n" % conf['socket']

    cfg_file = conf_dir + "/mysql.cfg"
    file(cfg_file, "w").write(content)

bakery_info["heinlein_mysql"] = {
    "bake_function" : bake_heinlein_mysql,
    "os"            : [ "linux" ],
}
