#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# .------------------------------------------------------------------------.
# |                ____ _               _        __  __ _  __              |
# |               / ___| |__   ___  ___| | __   |  \/  | |/ /              |
# |              | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /               |
# |              | |___| | | |  __/ (__|   <    | |  | | . \               |
# |               \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\              |
# |                                        |_____|                         |
# |             _____       _                       _                      |
# |            | ____|_ __ | |_ ___ _ __ _ __  _ __(_)___  ___             |
# |            |  _| | '_ \| __/ _ \ '__| '_ \| '__| / __|/ _ \            |
# |            | |___| | | | ||  __/ |  | |_) | |  | \__ \  __/            |
# |            |_____|_| |_|\__\___|_|  | .__/|_|  |_|___/\___|            |
# |                                     |_|                                |
# |                     _____    _ _ _   _                                 |
# |                    | ____|__| (_) |_(_) ___  _ __                      |
# |                    |  _| / _` | | __| |/ _ \| '_ \                     |
# |                    | |__| (_| | | |_| | (_) | | | |                    |
# |                    |_____\__,_|_|\__|_|\___/|_| |_|                    |
# |                                                                        |
# | mathias-kettner.com                                 mathias-kettner.de |
# '------------------------------------------------------------------------'
#  This file is part of the Check_MK Enterprise Edition (CEE).
#  Copyright by Mathias Kettner and Mathias Kettner GmbH.  All rights reserved.
#
#  Distributed under the Check_MK Enterprise License.
#
#  You should have  received  a copy of the Check_MK Enterprise License
#  along with Check_MK. If not, email to mk@mathias-kettner.de
#  or write to the postal address provided at www.mathias-kettner.de


def bake_heinlein_mysql(opsys, conf, conf_dir, plugins_dir):
    target_dir = plugins_dir

    # Handle the optional async/interval flag
    if "interval" in conf:
        target_dir = plugins_dir + "/%d" % conf["interval"] # Interval for async execution
        if not os.path.exists(target_dir):
            os.makedirs(target_dir)

    # Deploy the agent plugin
    shutil.copy2(agents_dir + "/plugins/heinlein_mysql", target_dir + "/heinlein_mysql")

    # Create the agent configuration
    content = agent_file_header
    if "credentials" in conf:
        content += "[client]\n" \
                   "user=%s\n" \
                   "password=\"%s\"\n" % conf['credentials']
    if "socket" in conf:
        content += "socket=%s\n" % conf['socket']

    cfg_file = conf_dir + "/mysql.cfg"
    file(cfg_file, "w").write(content)

bakery_info["heinlein_mysql"] = {
    "bake_function" : bake_heinlein_mysql,
    "os"            : [ "linux" ],
}
