#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_dell_idrac_vdisk(info):
    return [ (x[0] , None) for x in info ]

def check_dell_idrac_vdisk(item, params, info):
    vdisk_state = {
        1  : 'Unknown',
        2  : 'Online',
        3  : 'Failed',
        4  : 'Degraded',
        }
    vdisk_layout = {
        1 : 'Other',
        2 : 'Raid-0',
        3 : 'Raid-1',
        4 : 'Raid-5',
        5 : 'Raid-6',
        6 : 'Raid-10',
        7 : 'Raid-50',
        8 : 'Raid-60',
        9 : 'Concatenated Raid-1',
        10 : 'Concatenated Raid-5',
        }

    for line in info:
        if line[0] != item:
            continue
        state = saveint(line[3])
        try:
            info_text = "%s %s %s" % (line[2], vdisk_layout[saveint(line[4])], vdisk_state[state])
        except KeyError:
            info_text = "%d %d" % (state, cstate)
        if state in [2]:
            return (0, info_text)
        if state in [1, 4]:
            return (1, info_text)
        if state in [3]:
            return (2, info_text)
        return (3, info_text)
    return (3, "vDisk %s not found" % item)

check_info["dell_idrac_vdisk"] = {
    'check_function'        : check_dell_idrac_vdisk,
    'inventory_function'    : inventory_dell_idrac_vdisk,
    'service_description'   : 'iDRAC vD %s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.10892.5.5.1.20.140.1.1', [
        '1',  # virtualDiskNumber
        '2',  # virtualDiskName
        '3',  # virtualDiskDeviceName
        '4',  # virtualDiskState
        '13', # virtualDiskLayout
    ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.674.10892.5.5.1.20.140.1.1.1.1") != None,
}

