#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_dell_omsa_fan(info):
    inventory = []
    for line in info:
        inventory.append(( line[0], None ))
    return inventory

def check_dell_omsa_fan(item, params, info):
    fan_state = {
        0  : 'Unknown',
        1  : 'Ready',
        2  : 'Failed',
        3  : 'Online',
        4  : 'Offline',
        6  : 'Degraded',
        21 : 'Missing',
        }
    for line in info:
        if line[0] != item:
            continue
        state = int(line[2])
        try:
            info_text = "%s: State %s, Current Value %s" % (line[1],
                                                            fan_state[state],
                                                            line[3],
                                                            )
        except KeyError:
            info_text = "%s %d %s" % (line[1], state, line[3])
        if state in [1, 3]:
            return (0, info_text)
        if state in [4, 6]:
            return (1, info_text)
        if state in [2, 21]:
            return (2, info_text)
        return (3, info_text)
    return (3, "Fan %s not found" % item)

check_info["dell_omsa_fan"] = {
    'check_function'        : check_dell_omsa_fan,
    'inventory_function'    : inventory_dell_omsa_fan,
    'service_description'   : 'OMSA Fan%s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.10893.1.20.130.7.1', ['1',  # fanNumber
                                                                       '2',  # fanName
                                                                       '4',  # fanState
                                                                       '11', # fanProbeCurrValue
                                                                       ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.674.10893.1.20.130.7.1.1.1") != None,
}

