#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_dell_omsa_pdisk(info):
    inventory = []
    for line in info:
        inventory.append(( line[0], None ))
    return inventory

def check_dell_omsa_pdisk(item, params, info):
    spare_state = {
         1  : 'VD member',    # disk is a member of a virtual disk
         2  : 'DG member',    # disk is a member of a disk group
         3  : 'Global HS',    # disk is a global hot spare
         4  : 'Dedicated HS', # disk is a dedicated hot spare
         5  : 'no',           # not a spare
         99 : 'n/a',          # not applicable
         }
    pdisk_state = {
         0  : 'Unknown',
         1  : 'Ready',
         2  : 'Failed',
         3  : 'Online',
         4  : 'Offline',
         6  : 'Degraded',
         7  : 'Recovering',
         11 : 'Removed',
         13 : 'Non-RAID',
         14 : 'Not Ready',
         15 : 'Resynching',
         22 : 'Replacing',
         23 : 'Spinning Down',
         24 : 'Rebuilding',
         25 : 'No Media',
         26 : 'Formatting',
         28 : 'Diagnostics',
         34 : 'Predictive failure',
         35 : 'Initializing',
         39 : 'Foreign',
         40 : 'Clear',
         41 : 'Unsupported',
         53 : 'Incompatible',
         56 : 'Read Only',
         }
    for line in info:
        if line[0] != item:
            continue
        state = int(line[2])
        cstate = int(line[6])
        try:
            info_text = "%s %s E%s C%s is %s (Spare: %s)" % (line[1], line[3].strip(), line[4], line[5], pdisk_state[state], spare_state[cstate])
        except KeyError:
            info_text = "%d %d" % (state, cstate)
        if state in [1, 3, 13]:
            return (0, info_text)
        if state in [6, 14, 15, 24, 26, 34, 35]:
            return (1, info_text)
        if state in [0]:
            return (3, info_text)
        return (2, info_text)
    return (3, "Disk %s not found" % item)

check_info["dell_omsa_pdisk"] = {
    'check_function'        : check_dell_omsa_pdisk,
    'inventory_function'    : inventory_dell_omsa_pdisk,
    'service_description'   : 'OMSA Disk%s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.10893.1.20.130.4.1', ['1',  # Index
                                                                       '2',  # arrayDiskName
                                                                       '4',  # arrayDiskState
                                                                       '6',  # arrayDiskProductID
                                                                       '9',  # arrayDiskEnclosureID
                                                                       '10', # arrayDiskChannel
                                                                       '22', # arrayDiskSpareState
                                                                       ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.674.10893.1.20.130.4.1.1.1") != None,
}

