#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_dell_idrac_vdisk(info):
    return [ (x[0] , None) for x in info ]

def check_dell_idrac_vdisk(item, params, info):
    vdisk_state = {
        1  : 'Unknown',
        2  : 'Online',
        3  : 'Failed',
        4  : 'Degraded',
        }
    vdisk_layout = {
        1  : 'Concatenated',
        2  : 'RAID-0',
        3  : 'RAID-1',
        4  : 'UNSUPPORTED:raid-2',
        5  : 'UNSUPPORTED:raid-3',
        6  : 'UNSUPPORTED:raid-4',
        7  : 'RAID-5',
        8  : 'RAID-6',
        9  : 'UNSUPPORTED:raid-7',
        10 : 'RAID-10',
        11 : 'UNSUPPORTED:raid-30',
        12 : 'RAID-50',
        13 : 'UNSUPPORTED:addSpares',
        14 : 'UNSUPPORTED:deleteLogical',
        15 : 'UNSUPPORTED:transformLogical',
        18 : 'UNSUPPORTED:raid-0-plus-1',
        19 : 'Concatenated RAID-1',
        20 : 'UNSUPPORTED:concatRaid-5',
        21 : 'UNSUPPORTED:noRaid',
        22 : 'UNSUPPORTED:volume',
        23 : 'UNSUPPORTED:raidMorph',
        24 : 'RAID-60',
        25 : 'CacheCade',
        }
    for line in info:
        if line[0] != item:
            continue
        state = saveint(line[3])
        try:
            info_text = "%s %s %s" % (line[2], vdisk_layout[saveint(line[4])], vdisk_state[state])
        except KeyError:
            info_text = "%d %d" % (state, cstate)
        if state in [2]:
            return (0, info_text)
        if state in [1, 4]:
            return (1, info_text)
        if state in [3]:
            return (2, info_text)
        return (3, info_text)
    return (3, "vDisk %s not found" % item)

check_info["dell_idrac_vdisk"] = {
    'check_function'        : check_dell_idrac_vdisk,
    'inventory_function'    : inventory_dell_idrac_vdisk,
    'service_description'   : 'iDRAC vD %s',
    'has_perfdata'          : False,
    'snmp_info'             : ('.1.3.6.1.4.1.674.10892.5.5.1.20.140.1.1', [
        '1',  # virtualDiskNumber
        '2',  # virtualDiskName
        '3',  # virtualDiskDeviceName
        '4',  # virtualDiskState
        '13', # virtualDiskLayout
    ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.674.10892.5.5.1.20.140.1.1.1.1") != None,
}

