#!/bin/sh

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

if [ -e "$MK_CONFDIR/dir_size_ls.cfg" ]
then
    echo '<<<dir_size_ls>>>'
    grep "^\/.*\/" $MK_CONFDIR/dir_size_ls.cfg | \
    while read path
    do 
        ls -ld $path | awk '{ print $5 " " $9 }'
    done
fi

