#!/usr/bin/php
# Cachet Dashboard
<?php

if ($_SERVER['NOTIFY_WHAT'] != 'SERVICE') {
    echo "Not a service notification\n";
    exit(2);
}

if (!$_SERVER['NOTIFY_PARAMETER_CACHET_URL'] || !$_SERVER['NOTIFY_PARAMETER_API_KEY']) {
    echo "URL or API key not set\n";
    exit(2);
}

$cachet_url = $_SERVER['NOTIFY_PARAMETER_CACHET_URL']."/api/v1/";
$api_key = $_SERVER['NOTIFY_PARAMETER_API_KEY'];

if ($_SERVER['NOTIFY_PARAMETER_INCIDENT_PREFIX']) {
    $incident_prefix = $_SERVER['NOTIFY_PARAMETER_INCIDENT_PREFIX'];
} else {
    $incident_prefix = '[Nagios]';
}

$cachet_notify_subscribers = true; // Enable subscribers notifcation for incidents creation and updates
$cachet_incident_visible = $_SERVER['NOTIFY_PARAMETER_INCIDENT_VISIBLE'];

$cachet_component = $_SERVER['NOTIFY_PARAMETER_CACHET_COMPONENT'];
$service_name = $_SERVER['NOTIFY_SERVICEDESC'];
$service_status = $_SERVER['NOTIFY_SERVICESTATE'];
$service_status_type = 'HARD';
$service_output = $_SERVER['NOTIFY_SERVICEOUTPUT'];

define('CACHET_STATUS_INVESTIGATING', 1);
define('CACHET_STATUS_IDENTIFIED', 2);
define('CACHET_STATUS_WATCHING', 3);
define('CACHET_STATUS_FIXED', 4);

define('CACHET_COMPONENT_STATUS_OPERATIONAL', 1);
define('CACHET_COMPONENT_STATUS_PERFORMANCE_ISSUES', 2);
define('CACHET_COMPONENT_STATUS_PARTIAL_OUTAGE', 3);
define('CACHET_COMPONENT_STATUS_MAJOR_OUTAGE', 4);

function cachet_query($api_part, $action = 'GET', $data = null) {
	global $api_key, $cachet_url;

	print_r($data);

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $cachet_url . $api_part);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

	if (in_array($action, array('GET', 'POST', 'PUT'))) {
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $action);
	}

	if ($data !== null && is_array($data)) {
		$ch_data = http_build_query($data);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $ch_data);
	}

	$ch_headers = array(
		'X-Cachet-Token: ' . $api_key
	);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $ch_headers);

	curl_setopt($ch, CURLOPT_HEADER, false); // Don't return headers
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // Return body
	$http_body = curl_exec($ch);
	$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
	curl_close($ch);

	return array('code' => $http_code, 'body' => json_decode($http_body));
}

/* Find Cachet component ID */
$result = cachet_query('components');
if ($result['code'] != 200) {
	echo 'Can\'t query components' . "\n";
	exit(1);
}
$cachet_component_id = false;
foreach ($result['body']->data as $component) {
	if ($cachet_component == $component->name) { // We nailed it
		$cachet_component_id = $component->id;
		break; // Yes, bad.
	}
}
if ($cachet_component_id === false) {
	echo 'Can\'t find component "' . $cachet_component . '"' . "\n";
	exit(1);
}

/*
Determine what to to:
 - if PROBLEM and SOFT then don't cry just yet
 - if PROBLEM and HARD then create incident
 - if RECOVERY and SOFT then update incident
 - if RECOVERY and HARD then update incident

PROBLEM = !OK = (WARNING | CRITICAL | UNKONWN)
RECOVERY = OK
*/
if ($service_status == 'WARNING' && ($service_status_type == 'SOFT' || $service_status_type == 'HARD')) { // Hope it will be back soon
	//echo 'KO SOFT: not doing anything' . "\n";
	//exit(0);
	echo 'WARNING SOFT: creating incident' . "\n";
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_WATCHING,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_PERFORMANCE_ISSUES,
		'notify' => $cachet_notify_subscribers,
	);
	$result = cachet_query('incidents', 'POST', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t create incident' . "\n";
		exit(2);
	}
} elseif ($service_status == 'CRITICAL' && $service_status_type == 'SOFT') { // Something went wrong, let's notify
	echo 'KO HARD: creating incident' . "\n";
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_WATCHING,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_PARTIAL_OUTAGE,
		'notify' => $cachet_notify_subscribers,
	);
	$result = cachet_query('incidents', 'POST', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t create incident' . "\n";
		exit(2);
	}
} elseif ($service_status == 'CRITICAL' && $service_status_type == 'HARD') { // Something went wrong, let's notify
	echo 'KO HARD: creating incident' . "\n";
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_INVESTIGATING,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_MAJOR_OUTAGE,
		'notify' => $cachet_notify_subscribers,
	);
	$result = cachet_query('incidents', 'POST', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t create incident' . "\n";
		exit(2);
	}
} elseif ($service_status == 'OK' && $service_status_type == 'SOFT') { // Recovery underway
	echo 'OK Soft: creating incident' . "\n";
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_FIXED,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_OPERATIONAL,
		'notify' => $cachet_notify_subscribers,
	);
	$result = cachet_query('incidents', 'POST', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t create incident' . "\n";
		exit(2);
	}

	echo 'OK SOFT: updating incident' . "\n";
	/* Get the incident ID */
	$results = cachet_query('incidents');
	if ($result['code'] != 200) {
		echo 'Can\'t get incidents' . "\n";
		exit(2);
	}
	$cachet_incident_id = false;
	foreach ($results['body']->data as $incident) {
		if (($incident->name == $incident_prefix . ' ' . $service_name) and ($incident->status != CACHET_STATUS_FIXED)) {
			$cachet_incident_id = $incident->id;
			break; // Yes, bad.
		}
	}
	if ($cachet_incident_id === false) {
		echo 'Can\'t find incident "' . $incident_prefix . ' ' . $service_name . '"' . "\n";
		exit(2);
	}

	/* Update the incident */
	$query = array(
		//'name' => $incident_prefix . ' ' . $service_name,
		//'message' => $service_output,
		'status' => CACHET_STATUS_FIXED,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_OPERATIONAL,
		'notify' => $cachet_notify_subscribers,
		// 'id' => $cachet_incident_id,
	);
	$result = cachet_query('incidents/' . $cachet_incident_id, 'PUT', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t update incident' . "\n";
		exit(2);
	}
} elseif ($service_status == 'OK' && $service_status_type == 'HARD') { // Recovery completed
	echo 'OK Hard: creating incident' . "\n";
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_FIXED,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_OPERATIONAL,
		'notify' => $cachet_notify_subscribers,
	);
	$result = cachet_query('incidents', 'POST', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t create incident' . "\n";
		exit(2);
	}

	echo 'OK HARD: updating incident' . "\n";
	/* Get the incident ID */
	$results = cachet_query('incidents');
	if ($result['code'] != 200) {
		echo 'Can\'t get incidents' . "\n";
		exit(2);
	}
	$cachet_incident_id = false;
	foreach ($results['body']->data as $incident) {
		if (($incident->name == $incident_prefix . ' ' . $service_name) and ($incident->status != CACHET_STATUS_FIXED)) {
			$cachet_incident_id = $incident->id;
			file_put_contents('/tmp/testing.txt', $cachet_incident_id . "\n" . $incident->id);
			break; // Yes, bad.
		}
	}
	if ($cachet_incident_id === false) {
		echo 'Can\'t find incident "' . $incident_prefix . ' ' . $service_name . '"' . "\n";
		exit(2);
	}

	/* Update the incident */
	$query = array(
		'name' => $incident_prefix . ' ' . $service_name,
		'message' => $service_output,
		'status' => CACHET_STATUS_FIXED,
		'visible' => $cachet_incident_visible,
		'component_id' => $cachet_component_id,
		'component_status' => CACHET_COMPONENT_STATUS_OPERATIONAL,
		'notify' => $cachet_notify_subscribers,
		// 'id' => $cachet_incident_id,
	);
	$result = cachet_query('incidents/' . $cachet_incident_id, 'PUT', $query);
	if ($result['code'] != 200) {
		echo 'Can\'t update incident' . "\n";
		exit(2);
	}
} else {
	echo 'Bad arguments' . "\n";
	exit(2);
}

exit(0);
