#!/bin/bash

APCACCESS=$(which apcaccess)

if [ -x "$APCACCESS" ]; then
  echo "<<<apcaccess:sep(58)>>>"
  for conf in /etc/apcupsd/apcupsd*.conf; do
    echo "[[$(basename $conf)]]"
    $APCACCESS -f $conf status
  done
fi
