#!/bin/bash

APCACCESS=$(which apcaccess)

if [ -x "$APCACCESS" ]; then
  echo "<<<apcaccess:sep(35)>>>"
  for conf in /etc/apcupsd/apcupsd*.conf; do
    echo "[[$(basename $conf)]]"
    $APCACCESS -f $conf status|sed -e 's/ *: /#/'
  done
fi
