#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#   .--pathnum-------------------------------------------------------------.
#   |                         _   _                                        |
#   |             _ __   __ _| |_| |__  _ __  _   _ _ __ ___               |
#   |            | '_ \ / _` | __| '_ \| '_ \| | | | '_ ` _ \              |
#   |            | |_) | (_| | |_| | | | | | | |_| | | | | | |             |
#   |            | .__/ \__,_|\__|_| |_|_| |_|\__,_|_| |_| |_|             |
#   |            |_|                                                       |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'

def parse_velocloud_pathnum(info):
    if info:
        return { 'pathnum': int(info[0][0]) }
    return None

def discover_velocloud_pathnum(parsed):
    yield (None, {})

def check_velocloud_pathnum(_no_item, _no_params, parsed):
    yield 0, "%d Paths active" % parsed['pathnum'], [ ( 'active_vpn_tunnels', parsed['pathnum'] ) ]

check_info["velocloud_pathnum"] = {
    "parse_function":       parse_velocloud_pathnum,
    "service_description":  "VeloCloud Paths",
    "inventory_function": discover_velocloud_pathnum,
    "check_function":       check_velocloud_pathnum,
    "has_perfdata":         True,
    "snmp_info":            (".1.3.6.1.4.1.45346.1.1.2.4.2",
                             ["1.0"]),
    "snmp_scan_function":   lambda oid: "VeloCloud" in oid(".1.3.6.1.2.1.1.1.0") and oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.8072.3.2.10",
}
