#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Check NAS filesystems of Huawei storage systems
#

def inventory_huawei_nasfs(info):
    for line in info:
        yield line[1], None

def check_huawei_nasfs(item, params, info):
    for line in info:
        if item == line[1]:
            if line[4]:
                msg = [ line[4] ]
            else:
                msg = []
            health = line[2]
            if health in huawei_health_states:
                msg.append('Health: %s' % huawei_health_states[health])
            else:
                msg.append('Health: unknown %s(?)' % health)
            state = line[3]
            if state in huawei_running_states:
                msg.append('State: %s' % huawei_running_states[state])
            else:
                msg.append('State: unknown %s(?)' % state)

            res = df_check_filesystem_list(item, params, [ (item, saveint(line[6]), saveint(line[7]), 0) ])

            return (res[0], "; ".join(msg + [res[1]]), res[2])

check_info['huawei_nasfs'] = {
    'inventory_function'     : inventory_huawei_nasfs,
    'check_function'         : check_huawei_nasfs,
    'service_description'    : 'Filesystem %s',
    'has_perfdata'           : True,
    'snmp_info'              : ( '.1.3.6.1.4.1.34774.4.1.23.7.6.1', [
                                   '1', # hwInfoFileSysID
                                   '2', # hwInfoFileSysName
                                   '3', # hwInfoFileSysHeathStatus
                                   '4', # hwInfoFileSysRunningStatus
                                   '5', # hwInfoFileSysDescription
                                   '7', # hwInfoFileSysAllocType
                                   '8', # hwInfoFileSysCapacity
                                   '18', # hwInfoFileSysAvailableCapacity
                                   '9', # hwInfoFileSysSnapshotReservePer
                                   '10', # hwInfoFileSysSnapshotUseCapacity
                                   '11', # hwInfoFileSysSectorSize
                                   '15', # hwInfoFileSysEnableCompression
                               ] ),
    'snmp_scan_function'     : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
    'group'                  : 'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
    'includes'               : [ 'df.include', 'huawei.include' ],
}

