#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Disk with temperature check
#

def inventory_huawei_disk(info):
    for line in info:
        yield line[0], { 'runningStatus': line[2], 'role': line[5], 'interfaceBandwidth': line[7], 'serial': line[12] }

def check_huawei_disk(item, params, info):
    for line in info:
        if line[0] == item:
            res = 0
            msg = "%s %s %s %s %s" % (get_bytes_human_readable(saveint(line[4])*1024*1024), huawei_disk_types[line[3]], line[11], line[9], line[12])
            if line[12] != params['serial']:
                res = 1
                msg += '(!)'
            msg += " %s" % line[10]
            msg += "; health %s" % huawei_health_states[line[1]]
            if line[1] in [ '3', '6', '8', '12']:
                res = 1
                msg += '(!)'
            elif line[1] != '1':
                res = 2
                msg += '(!!)'
            msg += '; %s' % huawei_running_states[line[2]]
            if line[2] != params['runningStatus']:
                res = 2
                msg += ', changed from %s(!!)' % huawei_running_states[params['runningStatus']]
            if line[5] != params['role']:
                res = 2
                msg += '; role has changed(!!)'
            msg += '; %d Gbit/s' % (saveint(line[7]) / 1000)
            if line[7] != params['interfaceBandwidth']:
                res = 2
                msg += ', changed from %d Gbit/s(!!)' % (saveint(params['interfaceBandwidth']) / 1000)
            msg += '; %s' % line[13]

            temp = saveint(line[8])
            tempres, tempmsg, perfdata = check_temperature(temp, params, 'huawei_disks_%s' % item)
            if tempres > res:
                res = tempres
            msg += "; %s" % tempmsg
           
            return (res, msg, perfdata)

check_info['huawei_disk'] = {
    'inventory_function'    : inventory_huawei_disk,
    'check_function'        : check_huawei_disk,
    'service_description'   : 'Disk %s',
    'has_perfdata'          : True,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.23.5.1.1', [ '4', # 0 hwInfoDiskLocation
                                                                     '2', # 1 hwInfoDiskHealthStatus
                                                                     '3', # 2 hwInfoDiskRunningStatus
                                                                     '5', # 3 hwInfoDiskType
                                                                     '6', # 4 hwInfoDiskCapacity
                                                                     '7', # 5 hwInfoDiskRole
                                                                     '8', # 6 hwInfoDiskSpeed
                                                                     '9', # 7 hwInfoDiskInterfaceBandwidth
                                                                     '11', # 8 hwInfoDiskTemperature
                                                                     '12', # 9 hwInfoDiskModel
                                                                     '13', # 10 hwInfoDiskFirmwareVersion
                                                                     '14', # 11 hwInfoDiskManufacturer
                                                                     '15', # 12 hwInfoDiskSerialNumber
                                                                     '18', # 13 hwInfoDiskDiskDomainName
                                  ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
    'group'                 : 'temperature',
    'includes'              : [ 'temperature.include', 'huawei.include' ],
}
