#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

import pprint

huawei_running_states = {
    '0': '--',
    '1': 'normal',
    '2': 'running',
    '3': 'not running',
    '4': 'not existed',
    '5': 'sleep in high temperature',
    '6': 'starting',
    '7': 'power failure protecting',
    '8': 'spin down',
    '9': 'started',
    '10': 'link up',
    '11': 'link down',
    '12': 'powering on',
    '13': 'powered off',
    '14': 'precopy',
    '15': 'copyback',
    '16': 'reconstruction',
    '17': 'expansion',
    '18': 'unformatted',
    '19': 'formatting',
    '20': 'unmapped',
    '21': 'initial synchronizing',
    '22': 'consistent',
    '23': 'synchronizing',
    '24': 'synchronized',
    '25': 'unsynchronized',
    '26': 'splited',
    '27': 'online',
    '28': 'offline',
    '29': 'locked',
    '30': 'enabled',
    '31': 'disabled',
    '32': 'balancing',
    '33': 'to be recoverd',
    '34': 'interrupted',
    '35': 'invalid',
    '36': 'not start',
    '37': 'queuing',
    '38': 'stopped',
    '39': 'copying',
    '40': 'completed',
    '41': 'paused',
    '42': 'reverse synchronizing',
    '43': 'activated',
    '44': 'restore',
    '45': 'inactive',
    '46': 'idle',
    '47': 'powering off',
    '48': 'charging',
    '49': 'charging completed',
    '50': 'discharging',
    '51': 'upgrading',
    '63': 'running normal',
    '64': 'running fail',
    '65': 'running success',
    '66': 'Running success',
    '67': 'Running failed',
    '68': 'Waiting',
    '69': 'Canceling',
    '70': 'Canceled',
    '71': 'About to synchronize',
    '72': 'Synchronizing data',
    '73': 'Failed to synchronize',
    '74': 'Fault',
    '75': 'Migrating',
    '76': 'Migrated',
    '77': 'Activating',
    '78': 'Deactivating',
    '79': 'Start failed',
    '80': 'Stop failed',
    '81': 'Decommissioning',
    '82': 'Decommissioned',
    '83': 'Recommissioning',
    '84': 'Replacing node',
    '85': 'Scheduling',
    '86': 'Pausing',
    '87': 'Suspending',
    '88': 'Suspended',
    '89': 'Overload',
    '90': 'To be switch',
    '91': 'Switching',
    '92': 'To be cleanup',
    '93': 'Forced start',
    '94': 'Error',
}

def inventory_huawei_info(info):
    if opt_debug:
        print info
    if len(info):
        return [(None, {'state': info[0][2]} )]

def check_huawei_info(item, params, info):
    deviceType = { 
        0: 'V1500',
        1: 'V1800',
        2: 'S2100',
        3: 'S2300',
        4: 'S5100',
        5: 'S5300',
        6: 'S5500',
        7: 'S5600',
        8: 'VIS',
        9: 'S2600',
        10: 'S6800E',
        11: 'V1500N',
        12: 'S2300E',
        13: 'COMMON (mixed)',
        15: 'N8000',
        16: 'S6900',
        17: 'S3900',
        18: 'S5500T',
        19: 'S5600T',
        20: 'S6800T',
        21: 'S6900-M100',
        22: 'S3900-M200',
        23: 'S3900-M300',
        24: 'S5900-M100',
        25: 'S8100',
        26: 'S5800T',
        27: 'V1600N',
        28: 'S5900-M200',
        29: 'N8001',
        30: 'S2600T',
        31: 'S8000-I',
        32: 'Dorado5100',
        33: 'T3200',
        34: 'T3500',
        35: 'N8000-R710',
        36: 'N8000-C2',
        40: 'N8000-C2-SYMC',
        42: 'S2900',
        43: 'S2200T',
        44: 'Dorado2100_G2',
        56: 'OceanStor 18500F',
        57: 'OceanStor 18500',
        58: 'OceanStor 18800',
        60: 'Dorado2100',
        61: '6800 V3',
        62: '6900 V3',
        63: '5600 V3',
        64: '5800 V3',
        65: 'T3200',
        66: 'WUSHAN_SQL',
        67: 'WUSHAN_HD',
        68: '5500 V3',
        69: '2600 V3',
        70: '5300 V3',
        401: 'N5000',
        800: 'VIS8200',
        801: 'VIS8400',
        802: 'VIS8600',
        803: 'VIS8800',
    }
    if opt_debug:
        print item
        print params
        print info
    if len(info):
        msg = '%s; serial: %s; version: %s; state: %s' % (deviceType[saveint(info[0][1])],
                                                          info[0][0],
                                                          info[0][3],
                                                          huawei_running_states[info[0][2]])
        res = 0
        if info[0][2] != params['state']:
            msg += ', changed from %s(!!)' % huawei_running_states[params['state']]
            res = 2
        return (res, msg)

check_info['huawei_info'] = {
    'inventory_function'    : inventory_huawei_info,
    'check_function'        : check_huawei_info,
    'service_description'   : 'Huawei Device Info',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.1', [ '1.0', # deviceId
                                                              '2.0', # deviceType
                                                              '3.0', # status
                                                              '6.0', # version
                                                          ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.4.1.34774.4.1.1.1.0'),
}

def inventory_huawei_capacity(info):
    if opt_debug:
        print info
    if len(info):
        return [('Total Capacity', None)]

def check_huawei_capacity(item, params, info):
    if opt_debug:
        print item
        print params
        print info
    if item == 'Total Capacity':
        used_mb = saveint(info[0][0])
        size_mb = saveint(info[0][1])
        avail_mb = size_mb - used_mb
        return df_check_filesystem_list(item, params, [ (item, size_mb, avail_mb) ])

check_info['huawei_capacity'] = {
    'inventory_function'    : inventory_huawei_capacity,
    'check_function'        : check_huawei_capacity,
    'service_description'   : '%s',
    'has_perfdata'          : True,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.1', [ '4.0', # usedCapacity
                                                              '5.0', # totalCapacity
                                                           ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.4.1.34774.4.1.1.4.0'),
    'group'                 : 'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
    'includes':                [ 'df.include' ],
}

def inventory_huawei_fcports(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        if line[1] != '0':
            yield (line[0], { 'status': line[1], 'configRate': line[2], 'mode': line[3], 'logicType': line[5], 'speedRate': line[6] } )

def check_huawei_fcports(item, params, info):
    states = {
        '0': 'down',
        '1': 'up',
        '2': 'faulty',
    }
    rates = {
        '-1': 'unknown',
        '0': 'auto',
        '1': '1 Gbit/s',
        '2': '2 Gbit/s',
        '4': '4 Gbit/s',
        '8': '8 Gbit/s',
        '16': '16 Gbit/s',
    }
    modes = {
        '-1': 'unknown',
        '1': 'fabric',
        '2': 'public-loop',
        '3': 'point-to-point',
    }
    types = {
        '1': 'service',
        '2': 'ibc',
        '3': 'ibs',
        '4': 'expansion',
        '5': 'management',
        '6': 'upsmanagement',
        '8': 'maintenance',
    }
    if opt_debug:
        print item
        print params
        print info    
    for portID, status, configRate, mode, WWN, logicType, speedRate in info:
        if portID == item:
            res = 0
            msg = 'WWN: %s; link is %s' % (WWN, states[status])
            if status == '2':
                res = 2
                msg += '(!!)'
            elif status != params['status']:
                res = 1
                msg += ', has changed from %s(!)' % states[params['status']]
            msg += '; configured rate: %s' % rates[configRate]
            if configRate != params['configRate']:
                if res == 0:
                    res = 1
                msg += ', has changed from %s(!)' % rates[params['configRate']]
            msg += '; speed: %s' % rates[speedRate]
            if speedRate != params['speedRate']:
                if res == 0:
                    res = 1
                msg += ', has changed from %s(!)' % rates[params['speedRate']]
            msg += '; port mode: %s' % modes[mode]
            if mode != params['mode']:
                res = 2
                msg += ', has changed from %s(!!)' % modes[params['mode']]
            msg += '; logic type is %s' % types[logicType]
            if logicType != params['logicType']:
                res = 2
                msg += ', has changed from %s(!!)' % types[params['logicType']]
            return (res, msg)

check_info['huawei_fcports'] = {
    'inventory_function'    : inventory_huawei_fcports,
    'check_function'        : check_huawei_fcports,
    'service_description'   : 'FC Port %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.7', [ '1.3', # hwStorageFCPortID
                                                                   '1.4', # hwStorageFCPortStatus
                                                                   '1.5', # hwStorageFCPortConfigRate
                                                                   '1.6', # hwStorageFCPortMode
                                                                   '1.7', # hwStorageFCPortWWN
                                                                   '1.8', # hwStorageFCPortLogicType
                                                                   '1.9', # hwStorageFCPortSpeedRate
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

def inventory_huawei_sasports(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        if line[1] != '0':
            yield (line[0], { 'status': line[1], 'configRate': line[2], 'logicType': line[4], 'speedRate': line[5] } )

def check_huawei_sasports(item, params, info):
    states = {
        '0': 'down',
        '1': 'up',
        '2': 'faulty',
    }
    rates = {
        '-1': 'unknown',
        '0': 'auto',
        '1': '1 Gbit/s',
        '2': '2 Gbit/s',
        '4': '4 Gbit/s',
        '8': '8 Gbit/s',
        '12': '12 Gbit/s',
        '16': '16 Gbit/s',
    }
    types = {
        '1': 'service',
        '2': 'ibc',
        '3': 'ibs',
        '4': 'expansion',
        '5': 'management',
        '6': 'upsmanagement',
        '8': 'maintenance',
    }
    if opt_debug:
        print item
        print params
        print info    
    for portID, status, configRate, WWN, logicType, speedRate in info:
        if portID == item:
            res = 0
            msg = 'WWN: %s; link is %s' % (WWN, states[status])
            if status == '2':
                res = 2
                msg += '(!!)'
            elif status != params['status']:
                res = 1
                msg += ', has changed from %s(!)' % states[params['status']]
            msg += '; configured rate: %s' % rates[configRate]
            if configRate != params['configRate']:
                if res == 0:
                    res = 1
                msg += ', has changed from %s(!)' % rates[params['configRate']]
            msg += '; speed: %s' % rates[speedRate]
            if speedRate != params['speedRate']:
                if res == 0:
                    res = 1
                msg += ', has changed from %s(!)' % rates[params['speedRate']]
            msg += '; logic type is %s' % types[logicType]
            if logicType != params['logicType']:
                res = 2
                msg += ', has changed from %s(!!)' % types[params['logicType']]
            return (res, msg)

check_info['huawei_sasports'] = {
    'inventory_function'    : inventory_huawei_sasports,
    'check_function'        : check_huawei_sasports,
    'service_description'   : 'SAS Port %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.8', [ '1.3', # hwStorageSASPortID
                                                                   '1.4', # hwStorageSASPortStatus
                                                                   '1.5', # hwStorageSASPortConfigRate
                                                                   '1.6', # hwStorageSASPortWWN
                                                                   '1.7', # hwStorageSASPortLogicType
                                                                   '1.8', # hwStorageSASPortSpeedRate
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

def inventory_huawei_iscsiports(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        if line[1] != '0':
            yield (line[0], { 'status': line[1], 'ip': line[2], 'netmask': line[3], 'bindMode': line[4], 'logicType': line[5] } )

def check_huawei_iscsiports(item, params, info):
    states = {
        '0': 'down',
        '1': 'up',
        '2': 'faulty',
    }
    types = {
        '1': 'service',
        '2': 'ibc',
        '3': 'ibs',
        '4': 'expansion',
        '5': 'management',
        '6': 'upsmanagement',
        '8': 'maintenance',
    }
    if opt_debug:
        print item
        print params
        print info
    for portID, status, ip, netmask, bindMode, logicType in info:
        if portID == item:
            res = 0
            msg = "IP: %s" % ip
            if ip != params['ip']:
                res = 2
                msg += '(!!)'
            msg += '/%s' % netmask
            if netmask != params['netmask']:
                res = 2
                msg += '(!!)'
            msg += '; link is %s' % states[status]
            if status != params['status']:
                res = 2
                msg += '(!!)'
            msg += '; logic type is %s' % types[logicType]
            if logicType != params['logicType']:
                res = 2
                msg += ', has changed from %s(!!)' % types[params['logicType']]
            return (res, msg)

check_info['huawei_iscsiports'] = {
    'inventory_function'    : inventory_huawei_iscsiports,
    'check_function'        : check_huawei_iscsiports,
    'service_description'   : 'iSCSI Port %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.9', [ '1.3', # hwStorageISCSIPortID
                                                                   '1.4', # hwStorageISCSIPortStatus
                                                                   '1.5', # hwStorageISCSIPortIP
                                                                   '1.6', # hwStorageISCSIPortNetMask
                                                                   '1.7', # hwStorageISCSIPortBindMode
                                                                   '1.8', # hwStorageSASPortLogicType
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

def inventory_huawei_frontports(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        if line[3] != '0':
            yield line[0], {'status': line[3]}

def check_huawei_frontports(item, params, info):
    types = {
        '0': 'SAS',
        '1': 'FC',
        '2': 'iSCSI',
        '5': 'iSCSI',
        '8': 'FCoE',
    }
    states = {
        '0': 'link down',
        '1': 'link up',
        '2': 'not exist',
        '3': 'link bad',
        '4': 'hardware error',
        '5': 'speed no match',
        '6': 'enable',
        '7': 'disable',
        '8': 'mac error',
        '9': 'lane no match',
    }
    if opt_debug:
        print item
        print params
        print info
    for portIndex, desc, type, status, address in info:
        if portIndex == item:
            res = 0
            msg = "%s %s port; address: %s; state is %s" % (desc, types[type], address, states[status])
            if status != params['status']:
                res = 2
                msg += '(!!)'
            return (res, msg)

check_info['huawei_frontports'] = {
    'inventory_function'    : inventory_huawei_frontports,
    'check_function'        : check_huawei_frontports,
    'service_description'   : 'Front Port %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.11', [ '1.1', # hwStorageFrontEndHostPortIfIndex
                                                                    '1.5', # hwStorageFrontEndHostPortDescription
                                                                    '1.2', # hwStorageFrontEndHostPortType
                                                                    '1.3', # hwStorageFrontEndHostPortStatus
                                                                    '1.4', # hwStorageFrontEndHostPortPhysAddress
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

def inventory_huawei_controller(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        yield line[0], { 'runningStatus': line[3] }

def check_huawei_controller(item, params, info):
    healthStates = {
        '1': 'normal',
        '2': 'fault',
        '3': 'preFail',
        '4': 'partiallyBroken',
        '5': 'degraded',
        '6': 'badSectorsFound',
        '7': 'bitErrorsFound',
        '8': 'consistent',
        '9': 'inconsistent',
        '10': 'busy',
        '11': 'noInput',
        '12': 'lowBattery',
        '13': 'singleLinkFault',
    }
    if opt_debug:
        print item
        print params
        print info
    for name, location, healthStatus, runningStatus, softVer, isMaster, BIOSVer in info:
        if name == item:
            res = 0
            msg = 'Location: %s; software version %s; BIOS version %s; health is %s' % (location, softVer, BIOSVer, healthStates[healthStatus])
            if healthStatus in ['2', '9']:
                res = 2
                msg += '(!!)'
            elif healthStatus != '1':
                res = 1
                msg += '(!)'
            msg += '; running status is %s' % huawei_running_states[runningStatus]
            if runningStatus != params['runningStatus']:
                res = 2
                msg += ', changed from %s(!!)' % huawei_running_states[params['runningStatus']]
            return (res, msg)

check_info['huawei_controller'] = {
    'inventory_function'    : inventory_huawei_controller,
    'check_function'        : check_huawei_controller,
    'service_description'   : 'Controller %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.12', ['1.2', # hwStorageControllerName
                                                                   '1.3', # hwStorageControllerLocation
                                                                   '1.4', # hwStorageControllerHealthStatus
                                                                   '1.5', # hwStorageControllerRunningStatus
                                                                   '1.6', # hwStorageControllerSoftVer
                                                                   '1.8', # hwStorageControllerIsMaster
                                                                   '1.13', # hwStorageControllerBIOSVer
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

def parse_huawei_luns(info):
    luninfo = {}
    for line in info[0]:
        luninfo[line[0]] = line[1:]
    for line in info[1]:
        luninfo[line[0]] += line[1:]
    return luninfo

def inventory_huawei_luns(parsed):
    if opt_debug:
        pprint.pprint(parsed)
    for item in parsed:
        yield item, {}

def check_huawei_luns(item, params, parsed):
    states = {
        '1': 'normal',
        '2': 'fault',
        '3': 'notformat',
        '4': 'formatting',
    }
    if opt_debug:
        print item
        print params
        print parsed
    if item in parsed:
        res = 0
        msg = 'WWN: %s; pool: %s; state: %s' % (parsed[item][0], parsed[item][11], states[parsed[item][1]])
        if parsed[item][2] == '2':
            res = 2
            msg += '(!!)'
        elif parsed[item][2] in ['3', '4']:
            res = 1
            msg += '(!)'
        read_bytes_per_sec = saveint(parsed[item][7]) * 1024 * 1024
        write_bytes_per_sec = saveint(parsed[item][8]) * 1024 * 1024
        iops = saveint(parsed[item][4]) + saveint(parsed[item][5])
        perfdata = [ ( 'read', read_bytes_per_sec ),
                     ( 'write', write_bytes_per_sec ),
                     ( 'ios', iops ),
                 ]
        msg += "; read %s/sec, write %s/sec, IOPS total %s/sec" % (get_bytes_human_readable(read_bytes_per_sec),
                                                                   get_bytes_human_readable(write_bytes_per_sec),
                                                                   iops)
        capacity = saveint(parsed[item][12]) * 1024 * 1024
        perfdata.append( ( 'capacity', "%sB" % capacity ) )
        msg += "; capacity: %s" % get_bytes_human_readable(capacity)

        return (res, msg, perfdata)

check_info['huawei_luns'] = {
    'inventory_function'    : inventory_huawei_luns,
    'check_function'        : check_huawei_luns,
    'parse_function'        : parse_huawei_luns,
    'service_description'   : 'LUN %s',
    'has_perfdata'          : True,
    'snmp_info'             : [ ( '.1.3.6.1.4.1.34774.4.1', [ '19.9.4.1.2',  # hwStorageLunName            
                                                              '19.9.4.1.3',  # hwStorageLunWWN             0
                                                              '19.9.4.1.11', # hwStorageLunStatus          1
                                                              '21.4.1.2',    # hwPerfLunHitRate            2
                                                              '21.4.1.3',    # hwPerfLunTotalIOPS          3
                                                              '21.4.1.4',    # hwPerfLunReadIOPS           4
                                                              '21.4.1.5',    # hwPerfLunWriteIOPS          5
                                                              '21.4.1.6',    # hwPerfLunTotalTraffic       6
                                                              '21.4.1.7',    # hwPerfLunReadTraffic        7
                                                              '21.4.1.8',    # hwPerfLunWriteTraffic       8
                                                              '21.4.1.9',    # hwPerfLunReadIORate         9
                                                              '21.4.1.10',   # hwPerfLunWriteIORate        10
                                                          ], ),
                                ( '.1.3.6.1.4.1.34774.4.1.23.4.8.1', [ '2',  # hwInfoLunName
                                                                       '4',  # hwInfoLunPoolName           11
                                                                       '5',  # hwInfoLunCapacity           12
                                                                       '6',  # hwInfoLunSubscribedCapacity 13
                                                                       '8',  # hwInfoLunSectorSize         14
                                                                   ] ),
                            ],
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
    'group'                 : 'disk_io',
}


def inventory_huawei_disk(info):
    if opt_debug:
        pprint.pprint(info)
    for line in info:
        yield line[0], { 'runningStatus': line[2], 'serial': line[12] }

def check_huawei_disk(item, params, info):
    if opt_debug:
        print item
        print params
        print info
    for line in info:
        if line[0] == item:
            res = 0
            perfdata = [ ( 'temp', saveint(line[8]) ) ]
            msg = "%s %s %s" % (line[11], line[9], line[12])
            if line[12] != params['serial']:
                res = 1
                msg += '(!)'
            msg += " %s" % line[10]
            return (res, msg, perfdata)

check_info['huawei_disk'] = {
    'inventory_function'    : inventory_huawei_disk,
    'check_function'        : check_huawei_disk,
    'service_description'   : 'Disk %s',
    'has_perfdata'          : True,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.23.5.1.1', [ '4', # 0 hwInfoDiskLocation
                                                                     '2', # 1 hwInfoDiskHealthStatus
                                                                     '3', # 2 hwInfoDiskRunningStatus
                                                                     '5', # 3 hwInfoDiskType
                                                                     '6', # 4 hwInfoDiskCapacity
                                                                     '7', # 5 hwInfoDiskRole
                                                                     '8', # 6 hwInfoDiskSpeed
                                                                     '9', # 7 hwInfoDiskInterfaceBandwidth
                                                                     '11', # 8 hwInfoDiskTemperature
                                                                     '12', # 9 hwInfoDiskModel
                                                                     '13', # 10 hwInfoDiskFirmwareVersion
                                                                     '14', # 11 hwInfoDiskManufacturer
                                                                     '15', # 12 hwInfoDiskSerialNumber
                                                                     '18', # 13 hwInfoDiskDiskDomainName
                                  ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}

#
# Template Code
#

def inventory_huawei(info):
    if opt_debug:
        pprint.pprint(info)

def check_huawei(item, params, info):
    if opt_debug:
        print item
        print params
        print info    

check_info['huawei'] = {
    'inventory_function'    : inventory_huawei,
    'check_function'        : check_huawei,
    'service_description'   : '%s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '', [ '', # 
                                      '', # 
                                      '', # 
                                      '', # 
                                      '', # 
                                      '', # 
                                  ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
}
