#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Huawei Device Information
#

def inventory_huawei_info(info):
    if len(info):
        return [(None, {'state': info[0][2]} )]

def check_huawei_info(item, params, info):
    if len(info):
        msg = '%s; serial: %s; version: %s; state: %s' % (huawei_device_types[saveint(info[0][1])],
                                                          info[0][0],
                                                          info[0][3],
                                                          huawei_running_states[info[0][2]])
        res = 0
        if info[0][2] != params['state']:
            msg += ', changed from %s(!!)' % huawei_running_states[params['state']]
            res = 2
        return (res, msg)

check_info['huawei_info'] = {
    'inventory_function'    : inventory_huawei_info,
    'check_function'        : check_huawei_info,
    'service_description'   : 'Huawei Device Info',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.1', [ '1.0', # deviceId
                                                              '2.0', # deviceType
                                                              '3.0', # status
                                                              '6.0', # version
                                                          ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.4.1.34774.4.1.1.1.0'),
    'includes'              : [ 'huawei.include' ],
}
