#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Total Capacity as filesystem check
#

def inventory_huawei_capacity(info):
    if len(info):
        return [('Total Capacity', None)]

def check_huawei_capacity(item, params, info):
    if item == 'Total Capacity':
        used_mb = saveint(info[0][0])
        size_mb = saveint(info[0][1])
        avail_mb = size_mb - used_mb
        return df_check_filesystem_list(item, params, [ (item, size_mb, avail_mb, 0) ])

check_info['huawei_capacity'] = {
    'inventory_function'     : inventory_huawei_capacity,
    'check_function'         : check_huawei_capacity,
    'service_description'    : '%s',
    'has_perfdata'           : True,
    'snmp_info'              : ( '.1.3.6.1.4.1.34774.4.1.1', [ '4.0', # usedCapacity
                                                              '5.0', # totalCapacity
                                                           ] ),
    'snmp_scan_function'     : lambda oid: oid('.1.3.6.1.4.1.34774.4.1.1.4.0'),
    'group'                  : 'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
    'includes'               : [ 'df.include' ],
}

