#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2019 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Generic Port check includes FC, SAS and iSCSI
#

def inventory_huawei_logicalport(info):
    for line in info:
        yield ("%s %s" % (line[1], line[0]), { 'runningStatus': line[2] })

def check_huawei_logicalport(item, params, info):
    for line in info:
        if item.split(" ")[-1] == line[0]:
            if line[3]:
                yield 0, "%s/%s" % (line[3], line[4])
            if line[5]:
                yield 0, "Gateway %s" % line[5]
            if line[6]:
                yield 0, "%s/%s" % (line[6], line[7])
            if line[8]:
                yield 0, "Gateway: %s" % line[8]
            if line[2] != params.get('runningStatus'):
                yield 2, "running state %s (was %s)" % (line[2], params.get('runningStatus'))
            yield 0, "Port %s" % line[15]
            if line[18] == u"1":
                yield 0, "Failover Group %s" % line[20]

check_info['huawei_logicalport'] = {
    'inventory_function'    : inventory_huawei_logicalport,
    'check_function'        : check_huawei_logicalport,
    'service_description'   : 'Logical Port %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.23.7.5.1', [ '1',  # 0  hwInfoLogicalPortID
                                                                     '2',  # 1  hwInfoLogicalPorttName
                                                                     '3',  # 2  hwInfoLogicalPortRunStatus
                                                                     '4',  # 3  hwInfoLogicalPortIPv4Addr
                                                                     '5',  # 4  hwInfoLogicalPortIPv4Mask
                                                                     '6',  # 5  hwInfoLogicalPortIPv4Gateway
                                                                     '7',  # 6  hwInfoLogicalPortIPv6Addr
                                                                     '8',  # 7  hwInfoLogicalPortIPv6Mask
                                                                     '9',  # 8  hwInfoLogicalPortIPv6Gateway
                                                                     '10', # 9  hwInfoLogicalPortRole
                                                                     '11', # 10 hwInfoLogicalPortSupportProt
                                                                     '12', # 11 hwInfoLogicalPortHomePortType
                                                                     '13', # 12 hwInfoLogicalPortHomePortID
                                                                     '14', # 13 hwInfoLogicalPortOwnerCtrlID
                                                                     '15', # 14 hwInfoLogicalPortCurrPortType
                                                                     '16', # 15 hwInfoLogicalPortCurrPortID
                                                                     '17', # 16 hwInfoLogicalPortWorkCtrlID
                                                                     '18', # 17 hwInfoLogicalPortActState
                                                                     '22', # 18 hwInfoLogicalPortFailOVEnable
                                                                     '23', # 19 hwInfoLogicalPortFailBackMode
                                                                     '24', # 20 hwInfoLogicalPortFailOVGName
                                  ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
    'includes'              : [ 'huawei.include' ],
}

