#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Controller
#

def inventory_huawei_controller(info):
    for line in info:
        yield line[0], { 'runningStatus': line[3] }

def check_huawei_controller(item, params, info):
    for name, location, healthStatus, runningStatus, softVer, isMaster, BIOSVer in info:
        if name == item:
            res = 0
            msg = 'Location: %s; software version %s; BIOS version %s; health is %s' % (location, softVer, BIOSVer, huawei_health_states[healthStatus])
            if healthStatus in ['2', '9']:
                res = 2
                msg += '(!!)'
            elif healthStatus != '1':
                res = 1
                msg += '(!)'
            msg += '; running status is %s' % huawei_running_states[runningStatus]
            if runningStatus != params['runningStatus']:
                res = 2
                msg += ', changed from %s(!!)' % huawei_running_states[params['runningStatus']]
            return (res, msg)

check_info['huawei_controller'] = {
    'inventory_function'    : inventory_huawei_controller,
    'check_function'        : check_huawei_controller,
    'service_description'   : 'Controller %s',
    'has_perfdata'          : False,
    'snmp_info'             : ( '.1.3.6.1.4.1.34774.4.1.19.8.12', ['1.2', # hwStorageControllerName
                                                                   '1.3', # hwStorageControllerLocation
                                                                   '1.4', # hwStorageControllerHealthStatus
                                                                   '1.5', # hwStorageControllerRunningStatus
                                                                   '1.6', # hwStorageControllerSoftVer
                                                                   '1.8', # hwStorageControllerIsMaster
                                                                   '1.13', # hwStorageControllerBIOSVer
                                                                 ] ),
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.2011.2.91',
    'includes'              : [ 'huawei.include' ],
}
