#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_mailman_queues(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/mailman_queues", plugins_dir + "/mailman_queues")

    if conf.has_key("queues"):

        f = file(conf_dir + "/mailman_queues", "w")
        f.write(agent_file_header)

        f.write("QUEUES=\"%s\"" % " ".join(conf["queues"]))

bakery_info["mailman_queues"] = {
    "bake_function" : bake_mailman_queues,
    "os"            : [ "linux", ],
}
