#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2021 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_calculate_arguments(params):

    args = '-d "%s"' % params.get('description')
    args += ' -l "%s"' % params.get('label')
    args += ' -m "%s"' % params.get('metric')
    args += ' -o "%s"' % params.get('levels_lower').__repr__()
    args += ' -u "%s"' % params.get('levels_upper').__repr__()
    args += ' -e "%s"' % params.get('expression').replace('\n', '')

    return args

def check_calculate_description(params):
    return '%s' % params.get('description')

active_check_info['calculate'] = {
    "command_line"        : "check_calculate $ARG1$",
    "argument_function"   : check_calculate_arguments,
    "service_description" : check_calculate_description,
    "has_perfdata"        : True,
}


