#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

postconf_default_values = [ ( 'soft_bounce', 'no' ) ]

def postconf_name(line):
    return line[0]

def inventory_postconf(checkname, info):
    inventory = []
    if len(info) > 0:
        inventory = [ ( None, None ) ]
    return inventory

def check_postconf(_no_item, params, info):
    postconf = {}

    if not params:
        return (0, "No Postfix configuration parameters to check.")

    if type(params) != type([]):
        return (3, "Parameters not in list form")

    for param in params:
        postconf[param[0]] = param[1]

    infotext = []
    rc = 0
    
    for line in info:
        key = line[0]
        value = " ".join(line[2:])

        if key in postconf:
            if value != postconf[key]:
                infotext.append("%s=%s (!) %s expected" % (key, value, postconf[key]))
                rc = 1
            else:
                infotext.append("%s=%s" % (key, value))
    if not infotext:
        return (3, "No Postfix Configuration item found")
    else:
        return (rc, ", ".join(infotext))

check_info['postconf'] = {
    'check_function':      check_postconf,
    'service_description': "Postfix Config",
    'has_perfdata':        False,
    'inventory_function':  inventory_postconf,
    'group':               'postconf',
}

check_default_levels['postconf'] = 'postconf_default_values'

factory_settings['postconf_default_values'] = postconf_default_values
