#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

postconf_default_values = { 'soft_bounce': 'no' }

def postconf_name(line):
    return line[0]

def inventory_postconf(checkname, info):
    inventory = []
    for line in info:
        for key, value in postconf_default_values.iteritems():
            if postconf_name(line) == key:
                inventory.append( ( postconf_name(line), {} ) )
    return inventory

def check_postconf(item, params, info):
    for line in info:
        if item == postconf_name(line) and item in params:
            value = " ".join(line[2:])
            infotext = "%s" % value
            rc = 0
            if value != params[item]:
                rc = 2
            return (rc, infotext)
    return (3, "Config item %s not found" % item)

check_info['postconf'] = {
    'check_function':      check_postconf,
    'service_description': "Postfix Config %s",
    'has_perfdata':        False,
    'inventory_function':  inventory_postconf,
    'group':               'postconf',
}

check_default_levels['postconf'] = 'postconf_default_values'

factory_settings['postconf_default_values'] = postconf_default_values
