#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Water Leakage Detector
# http://www.hw-group.com/products/HWg-WLD/WLD_water_leak_detection_en.html
#

from cmk.base.check_api import LegacyCheckDefinition
from cmk.base.config import check_info
from cmk.agent_based.v2 import all_of, any_of, contains, endswith, exists, OIDEnd, SNMPTree

def inventory_hwg_wld(info):
    for line in info:
        yield line[0], {}

def check_hwg_wld(item, _no_params, info):
    wldState = { '0': (3, 'invalid'),
                 '1': (0, 'normal'),
                 '3': (2, 'alarm'),
               }
    wldValue = { '0': (0, 'normal'),
                 '1': (2, 'flooded'),
                 '2': (1, 'disconnect'),
                 '3': (3, 'invalid')
               }
    for line in info:
        if item == line[0]:
            yield 0, 'Sensor ID %s has SN %s' % (line[3], line[2])
            yield wldState.get(line[1], '0')[0], 'State is %s' % wldState.get(line[1], '0')[1]
            yield wldValue.get(line[4], '3')[0], 'Value is %s' % wldValue.get(line[4], '3')[1]

check_info['hwg_wld'] = LegacyCheckDefinition(
    parse_function=lambda x: x,
    discovery_function=inventory_hwg_wld,
    check_function=check_hwg_wld,
    service_name='WLD %s',
    fetch=SNMPTree(
        base='.1.3.6.1.4.1.21796.4.5.4.1',
        oids=[
            '2', # wldName
            '3', # wldState
            '4', # wldSN
            '5', # wldID
            '6', # wldValue
        ]),
    detect=contains('.1.3.6.1.2.1.1.2.0', '.1.3.6.1.4.1.21796.4.1'),
)

