#!/bin/bash

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

if [ -d /sys/devices/system/cpu ]; then
  echo '<<<cpufreq>>>'
  for cpudir in /sys/devices/system/cpu/*/cpufreq; do
    cpuid=$(cat $cpudir/affected_cpus)
    governor=$(cat $cpudir/scaling_governor || echo unknown)
    cur_freq=$(cat $cpudir/scaling_cur_freq || echo unknown)
    min_freq=$(cat $cpudir/scaling_min_freq || echo unknown)
    max_freq=$(cat $cpudir/scaling_max_freq || echo unknown)
    if [ -n "$cpuid" ]; then
      for id in $cpuid; do
        echo "cpu$id $governor $cur_freq $min_freq $max_freq"
      done
    fi
  done
fi