#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import os.path
import socket
import sys
import rados
from pprint import pprint

class RadosCMD(rados.Rados):  # type: ignore[misc]
    def command_mon(self, cmd, params=None):
        data = {"prefix": cmd, "format": "json"}
        if params:
            data.update(params)
        return self.mon_command(json.dumps(data), b"", timeout=5)

    def command_mgr(self, cmd):
        return self.mgr_command(json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5)

    def command_osd(self, osdid, cmd):
        return self.osd_command(
            osdid, json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5
        )

    def command_pg(self, pgid, cmd):
        return self.pg_command(pgid, json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5)


def _load_plugin_config(mk_confdir: str) -> tuple[str, str]:
    ceph_config = "/etc/ceph/ceph.conf"
    ceph_client = "client.admin"

    try:
        with open(os.path.join(mk_confdir, "ceph.cfg"), "r") as config:
            content = config.readlines()
    except FileNotFoundError:
        return ceph_config, ceph_client

    for line in content:
        if "=" not in line:
            continue
        key, value = line.strip().split("=")
        if key == "CONFIG":
            ceph_config = value
        if key == "CLIENT":
            ceph_client = value

    return ceph_config, ceph_client

def main() -> int:
    ceph_config, ceph_client = _load_plugin_config(os.environ["MK_CONFDIR"])

    cluster = RadosCMD(conffile=ceph_config, name=ceph_client)
    cluster.connect()

    print("<<<df_v2>>>")

    res = cluster.command_mon("fs volume ls")
    if res[0] == 0:
        volumes = json.loads(res[1])
        for volume in volumes:
            volume_info = { "pools": { "data": [] } }
            vi_res = cluster.command_mon("fs volume info", { "vol_name": volume["name"] })
            if vi_res[0] == 0:
                volume_info = json.loads(vi_res[1])
            volume_pools = {}
            for pool in volume_info["pools"]["data"]:
                volume_pools[pool["name"]] = pool["avail"]
            svgs_res = cluster.command_mon("fs subvolumegroup ls", { "vol_name": volume["name"] })
            if svgs_res[0] == 0:
                svgs = json.loads(svgs_res[1])
                for subvolumegroup in svgs:
                    svs_res = cluster.command_mon("fs subvolume ls", { "vol_name": volume["name"], "group_name": subvolumegroup["name"] })
                    if svs_res[0] == 0:
                        svs = json.loads(svs_res[1])
                        for subvolume in svs:
                            svi_res = cluster.command_mon("fs subvolume info", { "vol_name": volume["name"], "sub_name": subvolume["name"], "group_name": subvolumegroup["name"] })
                            if svi_res[0] == 0:
                                svi = json.loads(svi_res[1])
                                used = int(svi["bytes_used"] / 1024)
                                if svi["bytes_quota"] == "infinite":
                                    total = int(volume_pools[svi["data_pool"]] / 1024) + used
                                else:
                                    total = int(svi["bytes_quota"] / 1024)
                                perc = int(used / total)
                                volume_full_name = volume["name"] + "." + subvolumegroup["name"] + "." + subvolume["name"]
                                print(svi["path"] + " cephfs " + str(total) + " " + str(used) + " " + str(total-used) + " " + str(perc) + "% " + volume_full_name)

if __name__ == "__main__":
    sys.exit(main())
