#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# (c) 2025 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


import json
import os
import os.path
import sys
import rados
import socket
from pprint import pprint

class RadosCMD(rados.Rados):  # type: ignore[misc]
    def command_mon(self, cmd, params=None):
        data = {"prefix": cmd, "format": "json"}
        if params:
            data.update(params)
        return self.mon_command(json.dumps(data), b"", timeout=5)

    def command_mgr(self, cmd):
        return self.mgr_command(json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5)

    def command_osd(self, osdid, cmd):
        return self.osd_command(
            osdid, json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5
        )

    def command_pg(self, pgid, cmd):
        return self.pg_command(pgid, json.dumps({"prefix": cmd, "format": "json"}), b"", timeout=5)


def _load_plugin_config(mk_confdir: str) -> tuple[str, str]:
    ceph_config = "/etc/ceph/ceph.conf"
    ceph_client = "client.admin"

    try:
        with open(os.path.join(mk_confdir, "ceph.cfg"), "r") as config:
            content = config.readlines()
    except FileNotFoundError:
        return ceph_config, ceph_client

    for line in content:
        if "=" not in line:
            continue
        key, value = line.strip().split("=")
        if key == "CONFIG":
            ceph_config = value
        if key == "CLIENT":
            ceph_client = value

    return ceph_config, ceph_client

def list_subvolumes(cluster, volume_pools, params):
    svs_res = cluster.command_mon("fs subvolume ls", params)
    if svs_res[0] == 0:
        svs = json.loads(svs_res[1])
        for subvolume in svs:
            svi_res = cluster.command_mon("fs subvolume info", dict(params, **{"sub_name": subvolume["name"]}))
            if svi_res[0] == 0:
                svi = json.loads(svi_res[1])
                used = int(svi["bytes_used"] / 1024)
                if svi["bytes_quota"] == "infinite":
                    total = int(volume_pools[svi["data_pool"]] / 1024) + used
                else:
                    total = int(svi["bytes_quota"] / 1024)
                perc = int(used / total)
                if "group_name" in params:
                    volume_full_name = params["vol_name"] + "." + params["group_name"] + "." + subvolume["name"]
                else:
                    volume_full_name = params["vol_name"] + "._nogroup." + subvolume["name"]
                print(svi["path"] + " cephfs " + str(total) + " " + str(used) + " " + str(total-used) + " " + str(perc) + "% " + volume_full_name)

def main() -> int:
    print("<<<df_v2>>>")

    ceph_config, ceph_client = _load_plugin_config(os.environ["MK_CONFDIR"])

    cluster = RadosCMD(conffile=ceph_config, name=ceph_client)
    cluster.connect()

    hostname = socket.gethostname().split(".", 1)[0]

    local_volumes = set()

    dump_res = cluster.command_mon("fs dump")
    if dump_res[0] == 0:
        dump = json.loads(dump_res[1])
        for fs in dump.get("filesystems", []):
            for data in fs["mdsmap"]["info"].values():
                if hostname in data["name"]:
                    local_volumes.add(fs["mdsmap"]["fs_name"])

    volumes_res = cluster.command_mon("fs volume ls")
    if volumes_res[0] == 0:
        volumes = json.loads(volumes_res[1])
        for volume in volumes:
            if volume["name"] not in local_volumes:
                continue
            volume_info = { "pools": { "data": [] } }
            vi_res = cluster.command_mon("fs volume info", { "vol_name": volume["name"] })
            if vi_res[0] == 0:
                volume_info = json.loads(vi_res[1])
            volume_pools = {}
            for pool in volume_info["pools"]["data"]:
                volume_pools[pool["name"]] = pool["avail"]
            list_subvolumes(
                cluster,
                volume_pools,
                { "vol_name": volume["name"] },
            )
            svgs_res = cluster.command_mon("fs subvolumegroup ls", { "vol_name": volume["name"] })
            if svgs_res[0] == 0:
                svgs = json.loads(svgs_res[1])
                for subvolumegroup in svgs:
                    list_subvolumes(
                        cluster,
                        volume_pools,
                        { "vol_name": volume["name"], "group_name": subvolumegroup["name"] }
                    )

if __name__ == "__main__":
    sys.exit(main())
