#!/bin/bash

# (C) 2011 Bastian Kuhn <mail@bastian-kuhn.de>

# (C) 2025 Heinlein Consulting GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2. This file is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

globfiles() (
  set +f
  shopt -u nullglob failglob
  IFS=
  while IFS= read -r -d '' filename; do
    printf '%s\0' $filename
  done
)

if [ -e "$MK_CONFDIR/dir_size.cfg" ]; then
    echo '<<<dir_size>>>'
    grep -v -e '^#' -e '^$' $MK_CONFDIR/dir_size.cfg | tr '\n' '\0' | globfiles | xargs -0 -n 1 du -s
fi
