#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_sslcertificates(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(local_agents_dir + "/plugins/sslcertificates", plugins_dir + "/sslcertificates")
    f = file(conf_dir + "/sslcertificates", "w")
    f.write(agent_file_header)

    dirs = []

    for entry in conf:
        dirs.extend(entry["directories"])

    f.write("\n")

    if dirs:
        f.write("CERT_DIRS=\"%s\"\n" % " ".join(dirs))

bakery_info["sslcertificates"] = {
    "bake_function" : bake_sslcertificates,
    "os"            : [ "linux", ],
    "matchtype"     : "all",
}
