#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_entropy_avail(checkname, info):
    inventory = []
    if len(info) > 0:
        inventory.append( ( None, [] ) )
    return inventory

def check_entropy_avail(item, params, info):
    entropy_info = {}
    for line in info:
        entropy_info[line[0]] = saveint(line[1])

    warn = entropy_info['poolsize'] / 2
    crit = entropy_info['poolsize'] / 4

    if 'entropy_avail' in entropy_info:
        info_text = "%d Bits entropy available. Pool size: %d Bits" % (entropy_info['entropy_avail'],
                                                                       entropy_info['poolsize'])
        perf_data = [ ( "entropy",
                        "%db" % entropy_info['entropy_avail'], warn, crit, 0, entropy_info['poolsize'] ) ]
        if entropy_info['entropy_avail'] < crit:
            return (2, info_text, perf_data)
        if entropy_info['entropy_avail'] < warn:
            return (1, info_text, perf_data)
        return (0, info_text, perf_data)
    return (3, "No Entropy Information found")

check_info['entropy_avail'] = {
    'check_function':      check_entropy_avail,
    'service_description': "Entropy Available",
    'has_perfdata':        True,
    'inventory_function':  inventory_entropy_avail,
    'group':               'entropy_avail',
}
