#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Gerd Stolz <Gerd.Stolz@sva.de>
# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_status:sep(44)>>>
#[[SID INSTANCE]]
#Version;;1.00.097.00.1434028111 (fa/newdb100_maint_rel)
#All Started;OK;Yes

def _sap_hana_status_item(instance, line):
    if line[0] == "All Started":
        line[0] = "Status"
    return "%s %s" % (line[0], instance)

def inventory_sap_hana_status(parsed):
    for instance,lines in parsed.items():
        for line in lines:
            if len(line) > 2:
                yield _sap_hana_status_item(instance, line), {}

def check_sap_hana_status(item, params, parsed):
    for instance,lines in parsed.items():
        for line in lines:
            if len(line) > 2 and item == _sap_hana_status_item(instance, line):
                if item.startswith("Version"): 
                    return 0, line[2]
                status = line[1]
                value = line[2]
                serviceOutput = "%s (Status: %s)" % (value, status)
                if status == "OK":
                    return 0, serviceOutput
                elif status == "UNKNOWN":
                    return 3, serviceOutput
                else:
                    return 2, serviceOutput

check_info["sap_hana_status"] = {
    "parse_function"          : parse_sap_hana,
    "check_function"          : check_sap_hana_status,
    "inventory_function"      : inventory_sap_hana_status,
    "service_description"     : "SAP HANA %s",
    "has_perfdata"            : False,
    "includes"                : [ 'sap_hana.include' ],
}
