#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_events:sep(59)>>>
#[[TST00]]
#open_events;0
#disabled_alerts;0
#high_alerts;0

def inventory_sap_hana_events(parsed):
    for instance,lines in parsed.items():
        yield instance, {}

def check_sap_hana_events(item, params, parsed):
    events = { 'open_events': (2, 'Unacknowledged Events'),
               'disabled_alerts': (1, 'Disabled Alerts'),
               'high_alerts': (2, 'High Alerts') }
    for instance,lines in parsed.items():
        if instance == item:
            for line in lines:
                status = 0
                if line[0] in events:
                    value = saveint(line[1])
                    if value > 0:
                        status = events[line[0]][0]
                    yield status, '%s: %d' % ( events[line[0]][1], value), [ ( line[0], value ) ]

check_info["sap_hana_events"] = {
    "parse_function"          : parse_sap_hana,
    "check_function"          : check_sap_hana_events,
    "inventory_function"      : inventory_sap_hana_events,
    "service_description"     : "SAP HANA Events %s",
    "has_perfdata"            : True,
    "includes"                : [ 'sap_hana.include' ],
}
