#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_proc:sep(59)>>>
#[[SID INSTANCE]]
#31000;daemon;15993;;YES;0;NONE
#31001;nameserver;16010;master;YES;0;MASTER
#31002;preprocessor;18033;;YES;0;NONE
#31003;indexserver;18138;master;YES;31015;MASTER
#31004;scriptserver;18140;master;YES;0;MASTER
#31006;webdispatcher;21478;;YES;0;NONE
#31007;xsengine;18142;;YES;0;NONE
#31010;compileserver;18031;;YES;0;NONE

def inventory_sap_hana_proc(parsed):
    if cmk.debug.enabled():
        pprint.pprint(parsed)
    for instance,lines in parsed.items():
        for line in lines:
            if len(line) > 2:
                item = "%s - %s" % (instance, line[1])
                yield item, { 'coordin': line[6] }

def check_sap_hana_proc(item, params, parsed):
    if cmk.debug.enabled():
        pprint.pprint(item)
        pprint.pprint(params)
        pprint.pprint(parsed)
    for instance,lines in parsed.items():
        for line in lines:
            itemname = "%s - %s" % (instance, line[1])
            if len(line) > 2 and item == itemname:
                port = saveint(line[0])
                pid = saveint(line[2])
                detail = line[3]
                act = line[4]
                sqlport = saveint(line[5])
                coordin = line[6]

                yield 0, "Running on Port %d with Process ID %d" % (port, pid)
                if coordin != params['coordin']:
                    yield 1, "Role has changed to %s from %s" % (coordin, params['coordin'])
                elif coordin != 'NONE':
                    yield 0, "Role is %s" % coordin
                if sqlport > 0:
                    yield 0, "SQL-Port is %d" % sqlport
                if act != 'YES':
                    yield 2, "not acting"

check_info["sap_hana_proc"] = {
    "parse_function"          : parse_sap_hana,
    "check_function"          : check_sap_hana_proc,
    "inventory_function"      : inventory_sap_hana_proc,
    "service_description"     : "SAP HANA Process %s",
    "has_perfdata"            : False,
    "includes"                : [ 'sap_hana.include' ],
}
