#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_memrate:sep(59)>>>
#[[TST00]]
#mem_rate;123;456

factory_settings["sap_hana_memrate_default_levels"] = {
    "levels" : ('perc_used', (70.0, 80.0))
}

def inventory_sap_hana_memrate(parsed):
    for instance,lines in parsed.items():
        for line in lines:
            if line[0] == 'mem_rate':
                yield instance, {}

def check_sap_hana_memrate(item, params, parsed):
    for instance,lines in parsed.items():
        if instance == item:
            for line in lines:
                if line[0] == 'mem_rate':
                    yield check_memory_simple(saveint(line[1]), saveint(line[2]), params)

check_info["sap_hana_memrate"] = {
    "parse_function"          : parse_sap_hana,
    "check_function"          : check_sap_hana_memrate,
    "inventory_function"      : inventory_sap_hana_memrate,
    "service_description"     : "SAP HANA Memory %s",
    "has_perfdata"            : True,
    "includes"                : [ 'sap_hana.include', 'memory.include' ],
    "default_levels_variable" : 'sap_hana_memrate_default_levels',
    "group"                   : 'sap_hana_memrate',
}
