#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_ess:sep(59)>>>
#[[TST00]]
#started;5
#active;yes

def inventory_sap_hana_ess(parsed):
    for instance,lines in parsed.items():
        yield instance, {}

def check_sap_hana_ess(item, params, parsed):
    for instance,lines in parsed.items():
        if instance == item:
            active = 'unknown'
            started = 0
            status = 0
            for line in lines:
                if line[0] == 'active':
                    active = line[1]
                elif line[0] == 'started':
                    started = int(line[1])
            msg = '%d Threads started' % started
            perfdata = [ ('threads', started) ]
            if started < 1:
                status = 2
                msg += state_markers[2]
            msg += ', active is %s' % active
            if active in [ 'unknown' ]:
                status = 3
                msg += state_markers[3]
            elif active in [ 'false', 'no' ]:
                status = 2
                msg += state_markers[2]
            return status, msg, perfdata
            

check_info["sap_hana_ess"] = {
    "parse_function"          : parse_sap_hana,
    "check_function"          : check_sap_hana_ess,
    "inventory_function"      : inventory_sap_hana_ess,
    "service_description"     : "SAP HANA ESS %s",
    "has_perfdata"            : False,
    "includes"                : [ 'sap_hana.include' ],
}
