#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Gerd Stolz <Gerd.Stolz@sva.de>
# (c) Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
#<<<sap_hana_status:sep(44)>>>
#[[TST00]]
#Version;;1.00.097.00.1434028111 (fa/newdb100_maint_rel)
#All Started;OK;Yes

# This will be parsed into
# parsed = {
#  u'PRH00': [[u'Version', u'', u'1.00.097.00.1434028111 (fa/newdb100_maint_rel)'], [u'All Started', u'OK', u'Yes']]
# }

def inventory_sap_hana_status(parsed):
    if cmk.debug.enabled():
        pprint.pprint(parsed)
    for instance,lines in parsed.items():
	for line in lines:
	    if len(line) > 2:
		if line[0] == "All Started":
		    line[0] = "Status"
                item = "%s - %s" % (instance, line[0])
	        yield item, {}

def check_sap_hana_status(item, params, parsed):
    if cmk.debug.enabled():
        pprint.pprint(item)
        pprint.pprint(params)
        pprint.pprint(parsed)
    for instance,lines in parsed.items():
	for line in lines:
          if line[0] == u"All Started": 
             line[0] = u"Status"
          itemname = "%s - %s" % (instance, line[0])
          if len(line) > 2 and item == itemname:
            status = line[1]
            value = line[2]
	    if item.endswith("Version"): 
		yield 0, line[2]		
	    elif item.endswith("Status"):
		    serviceOutput = "%s (Status: %s)" % (value,status)
		    if status == "OK":
			yield 0, serviceOutput
			return
		    elif status == "UNKNOWN":
			yield 3, serviceOutput
			return
		    else:
			yield 2, serviceOutput
			return
	    else:
			yield 3, "UNKNOWN item " + item

check_info["sap_hana_status"] = {
    "parse_function"	      : parse_sap_hana,
    "check_function"          : check_sap_hana_status,
    "inventory_function"      : inventory_sap_hana_status,
    "service_description"     : "SAP HANA %s",
    "has_perfdata"            : False,
    "includes"                : [ 'sap_hana.include' ],
}
