#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Output of doveadm replicator status

# Queued 'sync' requests        0                                                                          
# Queued 'high' requests        6766                                                                       
# Queued 'low' requests         2767                                                                       
# Queued 'failed' requests      20                                                                         
# Queued 'full resync' requests 2667                                                                       
# Waiting 'failed' requests     0                                                                          
# Total number of known users   38993

def inventory_dovereplstat(checkname, info):
    if opt_debug:
        print 'checkname = %s' % pprint.pformat(checkname)
        print 'info = %s' % pprint.pformat(info)
    if len(info) > 1:
        return [(None, None)]

def check_dovereplstat(item, params, info):
    if opt_debug:
        print 'item = %s' % pprint.pformat(item)
        print 'params = %s' % pprint.pformat(params)
        print 'info = %s' % pprint.pformat(info)
    perfdata = []
    msg = []
    rc = 0
    for line in info:
        key = None
        val = None
        res = 0
        if line[1] in [ "'sync'", "'high'", "'low'", "'failed'" ]:
            key = line[1][1:-1] + '_requests'
            val = saveint(line[3])
        if line[1] == "'full":
            key = 'full_resync_requests'
            val = saveint(line[4])
        if line[:-1] == [u'Total', u'number', u'of', u'known', u'users']:
            key = 'total_users'
            val = saveint(line[5])
        text = "%d %s" % (val, " ".join(line[:-1]))
        if key in params:
            if val > params[key][1]:
                res = 2
                text += '(!!)'
            elif val > params[key][0]:
                res = 1
                text += '(!)'
            if res > rc:
                rc = res
            perfdata.append((key, val, params[key][0], params[key][1]))
        else:
            perfdata.append((key, val))
        msg.append(text)
    return (rc, ", ".join(msg), perfdata)

check_info['dovereplstat'] = {
    'check_function':      check_dovereplstat,
    'service_description': "Dovecot Replicator Status",
    'has_perfdata':        True,
    'inventory_function':  inventory_dovereplstat,
    'group':               'dovereplstat',
}
