#!/usr/bin/env python3
# JIRA (Heinlein)
# Bulk: no

# (c) 2018 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2. This file is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# script gets all arguments via environment variables
# the most important are:
# - NOTIFY_PARAMETER_URL
# - NOTIFY_PARAMETER_USERNAME
# - NOTIFY_PARAMETER_PASSWORD
# - NOTIFY_PARAMETER_HOST_CUSTOMID as custom field id for the HOSTPROBLEMID
# - NOTIFY_PARAMETER_SERVICE_CUSTOMID as custom field id for the SERVICEPROBLEMID
# - NOTIFY_PARAMETER_SITE_CUSTOMID as custom field id for the OMD_SITE
# - NOTIFY_PARAMETER_PROJECT or NOTIFY_CONTACT_JIRAPROJECT
# - NOTIFY_PARAMETER_ISSUETYPE or NOTIFY_CONTACT_JIRAISSUETYPE
# - NOTIFY_PARAMETER_PRIORITY or NOTIFIY_CONTACT_JIRAPRIORITY or not set
# - NOTIFY_PARAMETER_RESOLUTION or NOTIFY_CONTACT_JIRARESOLUTION
# - NOTIFY_PARAMETER_USERNAME or NOTIFY_CONTACT_JIRAUSER as issue reporter
# - NOTIFY_PARAMETER_ADD_CUSTOMID or NOTIFY_CONTACT_JIRAADDCF as additional custom field id
# - NOTIFY_PARAMETER_ADD_CUSTOMVALUE or NOTIFY_CONTACT_JIRAADDCFVAL as additional custom field value
# - NOTIFY_PARAMETER_MONITORING

from jira import JIRA
from jira.exceptions import JIRAError
from cmk.notification_plugins import utils
import sys
import os
from pprint import pprint # type: ignore

def get_summary(context):
    notification_type = context["NOTIFICATIONTYPE"]
    message = context['HOSTNAME'] + " "
    if context['WHAT'] == 'SERVICE':
        if notification_type in [ "PROBLEM", "RECOVERY" ]:
            message += context['SERVICESTATE'] + " "
            message += context['SERVICEDESC']
    else:
        if notification_type in [ "PROBLEM", "RECOVERY" ]:
            message += "is " + context['HOSTSTATE']
    return message

def get_description(context):
    if context['WHAT'] == 'SERVICE':
        if context['LONGSERVICEOUTPUT']:
            return context['LONGSERVICEOUTPUT']
        else:
            return context['SERVICEOUTPUT']
    else:
        if context['LONGHOSTOUTPUT']:
            return context['LONGHOSTOUTPUT']
        else:
            return context['HOSTOUTPUT']

context = utils.collect_context()

notfound = []
for necessary in [
    "PARAMETER_URL",
    "PARAMETER_USERNAME",
    "PARAMETER_HOST_CUSTOMID",
    "PARAMETER_SERVICE_CUSTOMID",
]:
    if necessary not in context:
        notfound.append(necessary)
if notfound:
    sys.stderr.write("%s not set" % ",".join(notfound))
    sys.exit(2)

password = None

if context["PARAMETER_PASSWORD_1"] == "cmk_postprocessed":
    if context["PARAMETER_PASSWORD_2"] == "stored_password":
        password = utils.retrieve_from_passwordstore("store " + context["PARAMETER_PASSWORD_3_1"])
    if context["PARAMETER_PASSWORD_2"] == "explicit_password":
        password = context["PARAMETER_PASSWORD_3_2"]
        
if not password:
    print("No Password configured.")
    sys.exit(2)

jira = JIRA(server=context['PARAMETER_URL'], basic_auth=(context['PARAMETER_USERNAME'], password))

if len(sys.argv) > 1:
    if sys.argv[1] == '-f':
        pprint(jira.createmeta_issuetypes(projectIdOrKey=context['PARAMETER_PROJECT']))
    if sys.argv[1] == '-p':
        pprint(jira.priorities())
    sys.exit()

newissue = {
    'labels': ['monitoring', 'monitoring/hostname:' + context['HOSTNAME'] ],
    'summary': get_summary(context),
    'description': get_description(context),
}
if context['WHAT'] == 'SERVICE':
    newissue['labels'].append('monitoring/servicedesc:' + context['SERVICEDESC'].replace(" ", "_"))

if 'PARAMETER_PROJECT' in context:
    newissue['project'] = {'id': context['PARAMETER_PROJECT']}
if 'CONTACT_JIRAPROJECT' in context:
    newissue['project'] = {'id': context['CONTACT_JIRAPROJECT']}
if 'PARAMETER_ISSUETYPE' in context:
    newissue['issuetype'] = {'id': context['PARAMETER_ISSUETYPE']}
if 'CONTACT_JIRAISSUETYPE' in context:
    newissue['issuetype'] = {'id': context['CONTACT_JIRAISSUETYPE']}
if 'PARAMETER_PRIORITY' in context:
    newissue['priority'] = {'id': context['PARAMETER_PRIORITY']}
if 'CONTACT_JIRAPRIORITY' in context:
    newissue['priority'] = {'id': context['CONTACT_JIRAPRIORITY']}
# if 'PARAMETER_USERNAME' in context:
#     newissue['reporter'] = {'value': context['PARAMETER_USERNAME']}
# if 'CONTACT_JIRAUSER' in context:
#     newissue['reporter'] = {'value': context['CONTACT_JIRAUSER']}

if context["WHAT"] == "HOST":
    custom_field = int(context["PARAMETER_HOST_CUSTOMID"])
    custom_field_value = int(context["HOSTPROBLEMID"])
else:
    custom_field = int(context["PARAMETER_SERVICE_CUSTOMID"])
    custom_field_value = int(context["SERVICEPROBLEMID"])
newissue[f"customfield_{custom_field}"] = custom_field_value

if "PARAMETER_SITE_CUSTOMID" in context:
    site_field = int(context["PARAMETER_SITE_CUSTOMID"])
    site_name = os.getenv("OMD_SITE")
    newissue[f"customfield_{site_field}"] = site_name

# Additional custom field
add_cfid = False
if "PARAMETER_ADD_CUSTOMID" in context:
    add_cfid = context["PARAMETER_ADD_CUSTOMID"]
if "CONTACT_JIRAADDCF" in context:
    add_cfid = context["CONTACT_JIRAADDCF"]
add_cfval = False
if "PARAMETER_ADD_CUSTOMVALUE" in context:
    add_cfval = context["PARAMETER_ADD_CUSTOMVALUE"]
if "CONTACT_JIRAADDCFVAL" in context:
    add_cfval = context["CONTACT_JIRAADDCFVAL"]
if add_cfval and add_cfid:
    newissue[f"customfield_{add_cfid}"] = {"id": add_cfval}

if 'project' not in newissue:
    print("No JIRA project ID set, discarding notification")
    sys.exit(2)

if 'issuetype' not in newissue:
    print("No JIRA issue type ID set")
    sys.exit(2)

if context['NOTIFICATIONTYPE'] == 'PROBLEM':
    try:
        issue = jira.create_issue(fields=newissue)
    except JIRAError as err:
        print('Unable to create issue, JIRA response code %s, %s' % (err.status_code, err.text))
        print(newissue)
        sys.exit(2)
    print('Created %s' % issue.permalink())
    if 'PARAMETER_MONITORING' in context:
        url = context['PARAMETER_MONITORING']
        if url.endswith('/'):
            # remove trailing slash
            url = url[:-1]
        if context['WHAT'] == 'SERVICE':
            url += context['SERVICEURL']
        else:
            url += context['HOSTURL']
        try:
            rl = jira.add_simple_link(issue, {
                'url': url,
                'title': 'Monitoring'}
                )
        except JIRAError as err:
            print('Unable to create link in issue, JIRA response code %s, %s' % (err.status_code, err.text))
            sys.exit(0)
        print('Created JIRA simple link: %s' % rl)
elif context['NOTIFICATIONTYPE'] == 'RECOVERY':
    query = 'resolution is EMPTY AND project = "%s" AND issuetype = "%s" AND labels = "%s" AND cf[%d] = %d AND cf[%d] ~ "%s"' % (
        newissue['project']['id'],
        newissue['issuetype']['id'],
        ",".join(newissue['labels']),
        custom_field,
        custom_field_value,
        site_field,
        site_name,
    )

    resolution = None
    if 'PARAMETER_RESOLUTION' in context:
        resolution = context['PARAMETER_RESOLUTION']
    if 'CONTACT_JIRARESOLUTION' in context:
        resolution = context['CONTACT_JIRARESOLUTION']

    if resolution == None:
        print("No JIRA resolution ID set")
        sys.exit(2)

    try:
        issues = jira.search_issues(query)
    except JIRAError as err:
        print('Unable to search, JIRA response code %s, %s' % (err.status_code, err.text))
        print("JIRA query: '%s'" % query)
        sys.exit(2)

    for issue in issues:
        try:
            jira.transition_issue(issue=issue, transition=resolution, comment=newissue['description'])
            print('Resolved %s' % issue.permalink())
        except JIRAError as err:
            print('Unable to resolve %s, JIRA response code %s, %s' % (issue.permalink(), err.status_code, err.text))

# -*- encoding: utf-8; py-indent-offset: 4 -*-
