#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_wireguard(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/wireguard", plugins_dir + "/wireguard")

bakery_info["wireguard"] = {
    "bake_function" : bake_wireguard,
    "os"            : [ "linux", ],
}
