#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

mailman_queues_default_values = ( 5000, 10000 )

def mailman_queues_name(line):
    return line[0]

def inventory_mailman_queues(checkname, info):
    inventory = []
    for line in info:
        inventory.append( ( mailman_queues_name(line), "mailman_queues_default_values" ) )
    return inventory

def check_mailman_queues(item, params, info):
    warn, crit = params
    for line in info:
        if item == mailman_queues_name(line):
            mails = int(line[3])
            bytes = int(line[4])
            rc = 0
            infotext = "%d mails" % mails
            perfdata = [ ( "length", mails, warn, crit),
                         ( "size", bytes ) ]
            if mails > crit:
                rc = 2
            elif mails > warn:
                rc = 1
            return (rc, infotext, perfdata)
    return (3, "Queue %s not found" % item, [])

check_info['mailman_queues'] = {
    'check_function':      check_mailman_queues,
    'service_description': "Mailman Queue %s",
    'has_perfdata':        True,
    'inventory_function':  inventory_mailman_queues,
    'group':               'mailman_queues',
}
