#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2017 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

uname_default_values = { }

def versiontuple(v):
    return tuple(map(int, (v.split("."))))

def parse_uname(info):
    if opt_debug:
        pprint.pprint(info)
    res = {}
    for line in info:
        res[line[0]] = " ".join(line[1:])
    return res

def inventory_uname(info):
    if opt_debug:
        pprint.pprint(info)
    if info:
        yield ( None, {} )

def check_uname(_no_item, params, info):
    if info:
        return 0, 'Kernel Release: %s, Kernel Version: %s' % (info['kernel-release'], info['kernel-version'])

check_info['uname'] = {
    'parse_function':      parse_uname,
    'inventory_function':  inventory_uname,
    'check_function':      check_uname,
    'service_description': "Kernel Version",
    'has_perfdata':        False,
    'group':               'uname',
    'default_levels_variable': 'uname_default_values',
}

factory_settings['uname_default_values'] = uname_default_values
