#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_lvm(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/lvm", plugins_dir + "/lvm")

bakery_info["lvm"] = {
    "bake_function" : bake_lvm,
    "os"            : [ "linux", ],
}
