#!/bin/bash

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

if [ -x /usr/sbin/postconf ]; then

  echo "<<<local>>>"

  defaultlimit=$(/usr/sbin/postconf -h default_process_limit)

  processes=$(ps -ef)

  /usr/sbin/postconf -M | awk '{ print $1 " " $2 " " $7 " " $8 ; }' | while read service type maxproc cmd; do

    if [ "$maxproc" = "-" ]; then
      maxproc=$defaultlimit
    fi
    warn=$((maxproc * 90 / 100))
    crit=$((maxproc * 98 / 100))

    count=""

    if [ "$cmd" = "smtpd" ]; then

      count=$(echo "$processes" | grep "$cmd -n $service -t $type" | wc -l)

    fi

    if [ "$service" = "smtp" -o "$service" = "lmtp" ]; then

      count=$(echo "$processes" | grep "$cmd -t $type" | wc -l)

    fi

    if [ -n "$count" ]; then
      if [ "$cmd" = "smtpd" ]; then
        echo -n "P Postfix_"
        echo -n "$cmd"
        echo "_$service count=$count;$warn;$crit;0;$maxproc Postfix port $service $cmd processes"
      else
        echo "P Postfix_$service count=$count;$warn;$crit;0;$maxproc Postfix $service processes"
      fi
   fi
  done
fi
