#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

postfix_mailq_details_default_values = ( 1000, 1500 )

def postfix_mailq_details_name(line):
    return line[0] + "_" + line[1]

def inventory_postfix_mailq_details(info):
    inventory = []
    for line in info:
        inventory.append( ( postfix_mailq_details_name(line), "postfix_mailq_details_default_values" ) )
    return inventory

def check_postfix_mailq_details(item, params, info):
    warn, crit = params
    for line in info:
        if item == postfix_mailq_details_name(line):
            mails = int(line[3])
            bytes = int(line[4])
            rc = 0
            if line[1] == 'age':
                if line[2][0] == '+':
                    infotext = "%d mails older than %s minutes" % (mails, line[2][1:])
                else:
                    infotext = "%d mails younger than %s minutes" % (mails, line[2][1:])
            else:
                infotext = "%d mails" % mails
            perfdata = [ ( "length", mails, warn, crit),
                         ( "size", bytes ) ]
            if mails > crit:
                rc = 2
            elif mails > warn:
                rc = 1
            return (rc, infotext, perfdata)
    return (3, "Queue %s not found" % item, [])

check_info['postfix_mailq_details'] = {
    'check_function':      check_postfix_mailq_details,
    'service_description': "Postfix Queue %s",
    'has_perfdata':        True,
    'inventory_function':  inventory_postfix_mailq_details,
    'group':               'postfix_mailq_details',
}

