#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_apcaccess(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/apcaccess", plugins_dir + "/apcaccess")

bakery_info["apcaccess"] = {
    "bake_function" : bake_apcaccess,
    "os"            : [ "linux", ],
}
