#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2016 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

netifaces_rbl_default_values = [ "cbl.abuseat.org", "b.barracudacentral.org", "zen.spamhaus.org", "ix.dnsbl.manitu.net" ]

def parse_netifaces(info):
    res = {}
    for iface, family, addr in info:
        if not res.has_key(iface):
            res[iface] = {}
        if not res[iface].has_key(family):
            res[iface][family] = []
        res[iface][family].append(addr)
    return res

def inventory_netifaces_rbl(info):
    inventory = []
    ifaces = parse_netifaces(info)
    for iface in ifaces.keys():
        for family in ifaces[iface].keys():
            if family == 'AF_INET':
                for addr in ifaces[iface][family]:
                    if addr != '127.0.0.1':
                        inventory.append( ( addr, netifaces_rbl_default_values ) )
    return inventory

def check_netifaces_rbl(item, rbls, info):
    import socket
    from pprint import pformat

    for iface, families in parse_netifaces(info).iteritems():
        for family, addresses in families.iteritems():
            for address in addresses:
                if item == address:
                    msg = ["bound on %s" % iface]
                    res = 0
                    count = 0
                    for rbl in rbls:
                        try:
                            ip = socket.gethostbyname("%s.%s." % (".".join(reversed(address.split('.'))), rbl))
                            res = 1
                            count += 1
                            msg.append('found in %s: %s (!)' % (rbl, ip))
                        except socket.gaierror:
                            pass
                    if count > 1:
                        res = 2
                        msg.append('found in more than 1 RBL (!!)')
                    return (res, ", ".join(msg))
    return (3, "%s not found" % item)

check_info["netifaces.rbl"] = {
    'check_function'        : check_netifaces_rbl,
    'inventory_function'    : inventory_netifaces_rbl,
    'service_description'   : 'RBL %s',
    'has_perfdata'          : False,
    'group'                 : 'netifaces_rbl',
}

check_default_levels['netifaces_rbl'] = 'netifaces_rbl_default_values'

factory_settings['netifaces_rbl_default_values'] = netifaces_rbl_default_values
