#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (C) 2019 Heinlein Support GmbH
# Robert Sander <r.sander@heinlein-support.de>
#

def agent_jenkins_arguments(servicespecs, hostname, ipaddress):    
    params = {'servicespecs': servicespecs,
              'hostname': hostname,
              'ipadress': ipaddress}

    import cPickle
    import base64

    cmd = []

    cmd += base64.encodestring(cPickle.dumps(params)).split('\n')

    return " ".join(cmd)

special_agent_info['jenkins'] = agent_jenkins_arguments
