#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2020 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

#
# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#
# Total Capacity as filesystem check
#

def inventory_stonesoft_firewall_partition(info):
    import cmk.utils.debug
    if cmk.utils.debug.enabled():
        print "info = ",
        pprint.pprint(info)
    for line in info:
        yield ( line[1], {} )

def check_stonesoft_firewall_partition(item, params, info):
    import cmk.utils.debug
    if cmk.utils.debug.enabled():
        print "item = ",
        pprint.pprint(item)
        print "params = ",
        pprint.pprint(params)
        print "info = ",
        pprint.pprint(info)
    for line in info:
        if line[1] == item:
            size_mb = saveint(line[2]) / 1024.0
            avail_mb = saveint(line[3]) / 1024.0
            return df_check_filesystem_list(item, params, [ (item, size_mb, avail_mb, 0) ])

check_info['stonesoft_firewall_partition'] = {
    'inventory_function'     : inventory_stonesoft_firewall_partition,
    'check_function'         : check_stonesoft_firewall_partition,
    'service_description'    : 'Filesystem %s',
    'has_perfdata'           : True,
    'snmp_info'              : ( '.1.3.6.1.4.1.1369.5.2.1.11.3.1', [ '2', # fwPartitionDevName
                                                                     '3', # fwMountPointName
                                                                     '4', # fwPartitionSize
                                                                     '6', # fwPartitionAvail
                                                                   ] ),
    'snmp_scan_function'     : lambda oid: oid('.1.3.6.1.2.1.1.2.0') == '.1.3.6.1.4.1.1369.5.2',
    'group'                  : 'filesystem',
    'default_levels_variable': 'filesystem_default_levels',
    'includes'               : [ 'size_trend.include', 'df.include' ],
}

