#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_atmedia_encryptor_status(info):
    return [ (line[0], line[1]) for line in info ]

def check_atmedia_encryptor_status(item, params, info):
    for line in info:
        name = line[0]
        if name != item: continue
        status = int(line[1])
	infotext = line[2]

        if status == 2:
            return (2, "%s" % infotext)
        if status == 3:
            return (1, "%s" % infotext)
        if status == 1:
            return (0, "%s" % infotext)
	return (3, "Status %d: %s" % (status, infotext))

    return (3, "%s not found in SNMP data" % item)


check_info["atmedia_encryptor_status"] = {
    'check_function':          check_atmedia_encryptor_status,
    'inventory_function':      inventory_atmedia_encryptor_status,
    'service_description':     'Encryptor %s',
    'has_perfdata':            False,
    'snmp_info':               ('.1.3.6.1.4.1.13458.1.4.2.2.1', [1, 2, 4]),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.4.1.13458.1.4.2.1.0"),
}

