#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_atmedia_temperature(_no_item, params, info):
    state = 0
    value = saveint(info[0][0]) / 100.0
    state_info = ""

    warn = ""
    crit = ""
    if params:
        warn = int(params.get('warn'))
        crit = int(params.get('crit'))
        if value > crit:
            state_info = "((!!) at %d°C)" % crit
            state = 2
        elif value > warn:
            state_info = "((!) at %d°C)" % warn
            state = 1

    infotext = "%s°C %s" % (value, state_info)
    return state, infotext, [("temp", value, warn, crit)]

check_info["atmedia_temperature"] = {
    'check_function'        : check_atmedia_temperature,
    'inventory_function'    : lambda info: len(info) > 0 and [(None, {'warn': 35, 'crit': 42})] or [],
    'service_description'   : "Temperature",
    'has_perfdata'          : True,
    'snmp_info'             : ('.1.3.6.1.4.1.13458.1.5', ["4.0" ] ),
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.4.1.13458.1.5.4.0") != None,
}

