#!/bin/bash

# (c) 2013 Heinlein Support GmbH
#          Robert Sander <r.sander@heinlein-support.de>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


echo '<<<dirvish>>>'

bank=/backup

for summary in $bank/*/current/summary; do

  bank=`grep ^Bank: $summary | cut -f 2 -d " "`
  vault=`grep ^vault: $summary | cut -f 2 -d " "`
  branch=`grep ^branch: $summary | cut -f 2 -d " "`
  client=`grep ^client: $summary | cut -f 2 -d " "`
  image=`grep ^Image: $summary | cut -f 2 -d " "`
  status=`grep ^Status: $summary | cut -f 2 -d " "`

  if [ -n "$status" ]; then
    echo -e $bank\\t$vault\\t$branch\\t$client\\t$image\\t$status
  else
    if grep -q ^Backup-begin $summary; then
      # Backup has started
      if grep -q ^Backup-complete $summary; then
        # Backup has ended, something strange happened
        echo -e $bank\\t$vault\\t$branch\\t$client\\t$image\\tunknown
      else
        # Backup is still running
        echo -e $bank\\t$vault\\t$branch\\t$client\\t$image\\trunning
      fi
    else
      # Backup has not started
      echo -e $bank\\t$vault\\t$branch\\t$client\\t$image\\tunknown
    fi 
  fi
done
